<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import AppDialog from '@/components/app/AppDialog.vue'
import AppSelect from '@/components/app/AppSelect.vue'
import { billingSpaceScopeDevices, contractAction, listResource, rootOrgs, saveContract } from '@/api/platform'
import { clearRequestCache } from '@/api/http'
import type { RecordRow } from '@/types/domain'
import contractStamp from '@/assets/contract-stamp.png'
const props=defineProps<{open:boolean}>(),emit=defineEmits<{ 'update:open':[boolean];saved:[] }>()
const orgs=ref<RecordRow[]>([]),tenants=ref<RecordRow[]>([]),spaces=ref<RecordRow[]>([]),availableDevices=ref<RecordRow[]>([]),deviceLoading=ref(false),saving=ref(false),error=ref('')
let errorTimer: ReturnType<typeof setTimeout> | undefined
watch(error,(value)=>{if(errorTimer)clearTimeout(errorTimer);if(value)errorTimer=setTimeout(()=>{error.value=''},3200)})
const form=reactive({tenantId:'',orgId:'',contractNo:`CT-${Date.now()}`,contractName:'能源计量结算合同',startDate:new Date().toISOString().slice(0,10),endDate:`${new Date().getFullYear()}-12-31`,spaceIds:[] as string[],meterIds:[] as string[]})
const spaceKeyword=ref(''),deviceKeyword=ref('')
const isSelectableSpace = (space: RecordRow) => !['DISABLED', 'INACTIVE'].includes(String(space.status ?? '').toUpperCase())
const activeSpaces = computed(() => spaces.value.filter(isSelectableSpace))
const filteredSpaces=computed(()=>{const q=spaceKeyword.value.trim().toLowerCase();const rows=activeSpaces.value;return q?rows.filter(x=>`${x.space_name||x.spaceName||''} ${x.space_code||x.spaceCode||''}`.toLowerCase().includes(q)):rows})
const filteredDevices=computed(()=>{const q=deviceKeyword.value.trim().toLowerCase();return q?availableDevices.value.filter(x=>`${x.device_name||x.deviceName||''} ${x.device_sn||x.deviceSn||''}`.toLowerCase().includes(q)):availableDevices.value})
let deviceRequest=0
watch(()=>form.spaceIds,async(ids)=>{form.meterIds=[];const token=++deviceRequest;if(!ids.length){availableDevices.value=[];return}deviceLoading.value=true;try{const rows=await billingSpaceScopeDevices(ids);if(token===deviceRequest)availableDevices.value=rows||[]}catch(e){if(token===deviceRequest){availableDevices.value=[];error.value=e instanceof Error?e.message:'设备范围加载失败'}}finally{if(token===deviceRequest)deviceLoading.value=false}},{deep:true})
async function load(){clearRequestCache('/archive/spaces');const r=await Promise.all([rootOrgs(),listResource('billing','tenants',{pageSize:500}),listResource('archive','spaces',{pageSize:500})]);orgs.value=r[0];tenants.value=r[1].records||[];spaces.value=r[2].records||[]}
async function save(){if(!form.tenantId||!form.orgId||!form.contractNo||!form.contractName){error.value='请填写合同编号、名称、租户和园区';return}if(!form.spaceIds.length||!form.meterIds.length){error.value='正式合同必须至少选择一个空间和一台设备';return}saving.value=true;try{const x=await saveContract({contractNo:form.contractNo,contractName:form.contractName,tenantId:Number(form.tenantId),orgId:Number(form.orgId),startDate:form.startDate,endDate:form.endDate,settlementDay:1,spaces:form.spaceIds.map(id=>({spaceId:Number(id),startDate:form.startDate})),meters:form.meterIds.map(id=>({deviceId:Number(id),startDate:form.startDate,meterFactor:1}))});if(x?.id)await contractAction(x.id,'activate');emit('update:open',false);emit('saved')}catch(e){error.value=e instanceof Error?e.message:'合同保存失败'}finally{saving.value=false}}
watch(() => props.open, (open) => { if (open) load() }, { immediate: true })
</script>
<template>
<AppDialog :open="props.open" @update:open="v=>emit('update:open',v)" title="新增能源计量结算合同" eyebrow="CONTRACT PREPARATION" hide-actions dialog-class="settlement-dialog contract-editor-dialog">
<article class="formal-contract"><header class="contract-heading"><div class="contract-code-label">ENERGY SETTLEMENT AGREEMENT</div><div class="contract-mark">能源计量结算合同</div><div class="contract-subtitle">（园区能源计量、费用结算及用能服务协议）</div><div class="contract-title-rule"><i></i><span>正式合同文本</span><i></i></div><div class="contract-heading-meta"><span>合同编号：<input v-model="form.contractNo" placeholder="由甲方统一编制"/></span><span>发起时间：<b>{{ new Date().toLocaleString('zh-CN') }}</b></span></div></header>
<Transition name="error-toast"><div v-if="error" class="error-toast"><span>⚠</span>{{error}}</div></Transition>
<section><h3>第一条　合同主体</h3><p>甲方：园区能源运营管理方（以下简称“甲方”）</p><p>乙方：<AppSelect v-model="form.tenantId"><option value="">请选择用能单位</option><option v-for="x in tenants" :key="String(x.id)" :value="String(x.id)">{{x.tenant_name||x.tenantName}}</option></AppSelect>（以下简称“乙方”）</p><p>所属园区：<AppSelect v-model="form.orgId"><option value="">请选择所属园区</option><option v-for="x in orgs" :key="String(x.id)" :value="String(x.id)">{{x.org_name}}</option></AppSelect></p><p>合同名称：<input v-model="form.contractName" class="wide-input"/></p></section>
<section><h3>第二条　合同目的与适用范围</h3><p>甲方为乙方提供园区内能源计量、数据采集、用能核算、费用结算及相关运营服务。乙方同意按照本合同约定使用结算空间、结算设备及其对应的计量计价规则，并按照甲方正式出具的账单及时支付应付费用。</p><p>本合同适用于水、电、气及其他经平台登记并纳入结算范围的能源品类。双方确认，系统经校验后的计量数据、计费明细、账单及收款记录共同构成结算依据。</p></section>
<section><h3>第三条　合同期限与发起</h3><p>本合同期限自 <input v-model="form.startDate" type="date"/> 起至 <input v-model="form.endDate" type="date"/> 止。合同创建并完成结算范围绑定后，由甲方确认启用；合同启用后，可按照约定的自动出账计划或甲方手动发起本期结算。</p><p>合同发起时间由平台留存，合同编号由甲方统一管理。合同生效后，乙方绑定空间、设备及计价规则的变更应当通过平台变更流程办理。</p></section>
<section><h3>第四条　结算范围</h3><div class="contract-selections"><label><span>绑定空间（可多选）</span><input v-model="spaceKeyword" class="selection-search" placeholder="搜索空间名称或编码"/><div class="contract-picker picker-list"><label v-for="x in filteredSpaces" :key="String(x.id)" class="picker-option"><input v-model="form.spaceIds" type="checkbox" :value="String(x.id)"/><span>{{x.space_name||x.spaceName}}<small>{{x.space_code||x.spaceCode}}</small></span></label><p v-if="!filteredSpaces.length" class="picker-empty">暂无可用空间</p></div><small class="selection-hint">已选择 {{form.spaceIds.length}} 个计费空间</small></label><label><span>绑定设备（来自空间映射范围，可多选）</span><input v-model="deviceKeyword" class="selection-search" placeholder="搜索设备名称或 SN"/><div class="contract-picker picker-list"><label v-for="x in filteredDevices" :key="String(x.id)" class="picker-option"><input v-model="form.meterIds" type="checkbox" :value="String(x.id)"/><span>{{x.device_name||x.deviceName||x.device_sn}}<small>{{x.device_sn||x.deviceSn||''}} · {{x.org_name||'组织未标注'}}{{x.gateway_name?` · ${x.gateway_name}`:''}}</small></span></label><p v-if="deviceLoading" class="picker-empty">正在读取组织/网关映射范围…</p><p v-else-if="!filteredDevices.length" class="picker-empty">{{form.spaceIds.length?'所选空间映射范围内暂无设备':'请先选择空间'}}</p></div><small class="selection-hint">已选择 {{form.meterIds.length }} 台设备</small></label></div><p>乙方确认上述空间和设备为本合同项下的实际用能及计量范围。设备更换、移交、停用或空间退租时，应按甲方要求办理交接和临时结算。</p></section>
<section><h3>第五条　计量、计费与账单</h3><p>甲方根据设备采集的原始读数、数据质量校验结果、计量倍率、换表记录及有效计费规则计算本期用量。原始上报数据发生缺失、异常跳变或其他质量问题时，甲方可依据校验规则进行修正，并保留修正过程及审计记录。</p><p>账单生成后进入“账单支付”模块。乙方应在账单载明的付款截止日前完成确认及支付；账单金额、用量明细、公摊费用、分时价格及调账记录以平台正式账单为准。</p></section>
<section><h3>第六条　付款、逾期与对账</h3><p>乙方可通过甲方认可的银行转账、线下对公或其他支付方式完成付款。甲方收到款项后，将收款流水与账单进行勾兑，支持部分付款和全额付款。账单结清后进入结算档案并按照财务规则归档。</p><p>乙方逾期未付款的，甲方可依据合同约定和平台规则计算逾期费用，并将欠费信息纳入应收台账。乙方对账单有异议的，应在付款截止日前提出，逾期未提出视为认可本期账单。</p></section>
<section><h3>第七条　变更、终止与档案</h3><p>合同空间、设备、规则和租户信息发生变化时，双方应通过平台办理变更。合同终止不影响终止日前已发生的能源费用、已生成账单、应收款项及相关审计记录。合同终止后，甲方可进行中途结算、销账、凭证和结算档案归档。</p><p>本合同及其附件、绑定范围、账单、计量明细、收款流水和变更日志由平台统一保存，作为双方后续核对、审计和争议处理的依据。</p></section>
<section><h3>第八条　其他约定</h3><p>本合同未尽事宜，按照甲方园区能源管理制度、收费标准、计量管理制度及双方另行签署的补充协议执行。若平台规则与本合同约定存在不一致，以双方确认的正式合同及经审核发布的计价方案为准。</p><p>本合同经甲方在平台确认启用后生效。乙方完成绑定信息确认，即视为已阅读并接受本合同项下的计量、计费、支付和归档规则。</p></section>
<section><h3>第九条　数据记录与审计</h3><p>甲方应按照数据最小必要、真实完整和可追溯原则保存原始抄表记录、数据校验结果、计量倍率、换表记录、人工修正、计费明细、账单、收款流水、凭证及操作日志。乙方有权在合理范围内查询与本合同有关的计量和结算记录，但不得擅自修改、删除、复制或向无关第三方披露平台数据。</p><p>因设备通信中断、数据缺失、异常跳变、设备更换或其他客观原因需要估算、补录或修正用量的，甲方应依据设备档案、历史数据、运维记录及适用规则处理，并在账单或变更记录中保留处理依据。双方对修正结果有异议的，应在账单异议期限内提交书面说明及相应证据。</p></section>
<section><h3>第十条　违约责任</h3><p>乙方未按约定期限足额支付能源费用、擅自拆改计量设施、转供能源、扩大使用范围、拒绝配合抄表或提供虚假资料的，应承担由此产生的补缴情形、逾期费用、设备恢复费用及甲方因此遭受的实际损失。甲方有权依据合同约定和园区管理制度采取催缴、限制新增用能、暂停非必要服务及其他必要措施。</p><p>甲方未按约提供可用的计量结算服务，或因甲方原因造成账单、收款记录严重错误的，应及时核查并采取补正、重算、冲红或重新出账措施。双方均应采取合理措施减少损失，不得以争议为由拒绝履行无争议部分的付款或配合义务。</p></section>
<section><h3>第十一条　保密与信息安全</h3><p>双方对在合同履行过程中知悉的对方商业信息、经营数据、能源用量、账户信息、联系人信息及其他未公开资料负有保密义务。除法律法规、监管要求、审计需要或获得对方书面授权外，任何一方不得向无关第三方披露或用于本合同以外的目的。</p><p>乙方应妥善保管平台账户、密码及授权凭据，不得共用、转借或委托无关人员操作。因乙方保管不善、越权操作或未及时报告异常造成的损失，由责任方依法承担；双方应配合完成安全事件排查和审计留痕。</p></section>
<section><h3>第十二条　争议解决与合同文本</h3><p>因本合同的订立、履行、变更、终止或结算产生争议的，双方应先依据平台记录、合同附件和对账记录进行核验，并通过协商解决；协商不成的，任一方可向甲方所在地有管辖权的人民法院提起诉讼。争议处理期间，除争议部分外，双方仍应继续履行其他无争议义务。</p><p>本合同正文、合同附件、空间和设备清单、计价方案、账单、收款记录、对账记录及经授权确认的电子操作留痕共同构成完整合同文件。电子合同与纸质合同具有同等业务效力；本合同未加盖公章的页面、草稿及未确认数据不作为正式结算依据。</p></section>
<footer class="contract-sign"><div>甲方（盖章）：<img :src="contractStamp" alt="合同专用章"/><br/>经办人：____________</div><div>乙方（盖章）：____________<br/>授权代表：____________</div></footer>
<footer class="contract-actions"><button class="quiet" @click="emit('update:open',false)">取消</button><button class="primary" :disabled="saving" @click="save">{{saving?'正在保存…':'确认启用合同'}}</button></footer></article></AppDialog>
</template>
<style scoped>
@media(max-width:760px){.contract-heading-meta{align-items:flex-start;flex-direction:column;gap:8px}.contract-heading-meta input{width:min(210px,58vw)}.contract-title-rule{width:min(270px,78vw)}}
.formal-contract{padding:30px 44px;color:#171717;background:#fff;font-family:Georgia,'Songti SC','SimSun',serif;line-height:1.9}.contract-heading{text-align:center;border-bottom:2px solid #222;padding-bottom:16px}.contract-mark{font-size:27px;font-weight:700;letter-spacing:.2em}.contract-heading p{margin:10px 0 0;font-size:12px;text-align:left}.formal-contract input,.formal-contract select{border:0;border-bottom:1px solid #777;border-radius:0;background:#fff;color:#111;padding:3px 6px;font-family:inherit}.formal-contract input[type=date]{width:145px}.formal-contract .wide-input{width:280px}.formal-contract section{margin-top:20px;border-top:1px solid #333;padding-top:10px}.formal-contract h3{margin:0 0 8px;font-size:15px}.formal-contract p{margin:6px 0;font-size:13px;text-indent:2em}.formal-contract .app-select{display:inline-block;vertical-align:middle;min-width:180px}.contract-selections{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:10px 0}.contract-selections label{font-size:13px}.contract-selections select{display:block;width:100%;height:120px;margin-top:6px;border:1px solid #777;padding:6px}.form-error{padding:9px 12px;border:1px solid #a33;color:#8d1d1d;background:#fafafa}.contract-sign{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:34px;padding-top:18px;border-top:2px solid #222;line-height:2.4;font-size:13px}.contract-sign i{display:inline-grid;place-items:center;width:72px;height:72px;border:2px solid #a01e2e;border-radius:50%;color:#a01e2e;font-style:normal;font-size:11px;transform:rotate(-12deg);margin-left:12px}.contract-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:24px;padding-top:16px;border-top:1px solid #222}@media(max-width:760px){.formal-contract{padding:22px}.contract-selections,.contract-sign{grid-template-columns:1fr;gap:12px}.contract-mark{font-size:21px}.formal-contract .app-select{min-width:140px}}
</style>
<style scoped>
.formal-contract{background:#fff!important;color:#111!important;min-height:100%;box-shadow:none}.formal-contract section{border-top:1px solid #222!important}.formal-contract .app-select-trigger{border:0!important;border-bottom:1px solid #777!important;border-radius:0!important;background:#fff!important;box-shadow:none!important}.formal-contract .contract-selections select{border:0;border-bottom:1px solid #777;padding-left:0}.formal-contract .contract-heading{border-bottom:2px solid #111!important}.formal-contract .contract-sign{border-top:2px solid #111!important}.contract-picker{display:block;width:100%;height:44px;margin-top:5px;padding:0 12px!important;border:1px solid #d9e1e8!important;border-radius:8px!important;background:#fbfdff!important;font-family:var(--font-body)!important;color:#253b51!important}.contract-selections label>span{display:block;color:#6e7e8d;font-size:11px;letter-spacing:.08em}.contract-sign img{width:74px;height:74px;object-fit:contain;vertical-align:middle;margin-left:10px}
.error-toast{position:fixed;z-index:3000;top:18px;left:50%;transform:translateX(-50%);display:flex;gap:8px;align-items:center;width:fit-content;max-width:min(680px,calc(100vw - 32px));padding:12px 18px;border:1px solid #efc9bd;border-radius:10px;background:#fff8f5;color:#a34730;box-shadow:0 12px 30px rgba(53,37,30,.16);line-height:1.5;overflow-wrap:anywhere}.error-toast-enter-active,.error-toast-leave-active{transition:opacity .28s,transform .28s}.error-toast-enter-from,.error-toast-leave-to{opacity:0;transform:translate(-50%,-18px)}
.selection-search{display:block;width:100%;height:36px;margin-top:9px;padding:0 10px!important;border:1px solid #d9e1e8!important;border-radius:8px!important;background:#fff!important;font-family:var(--font-body)!important}.contract-selections select[multiple].contract-picker{scrollbar-width:none}.contract-selections select[multiple].contract-picker::-webkit-scrollbar{display:none}.formal-contract{scrollbar-width:none}.formal-contract::-webkit-scrollbar{display:none}:deep(.contract-editor-dialog .dialog-content){scrollbar-width:none}:deep(.contract-editor-dialog .dialog-content::-webkit-scrollbar){display:none}.contract-sign>div:first-child{position:relative;min-height:132px}.contract-sign img{position:absolute;width:185px!important;height:185px!important;left:145px;top:-22px;object-fit:contain;z-index:1}.contract-sign{position:relative;min-height:155px}
.contract-selections{grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:16px 0}.contract-selections label{display:block;padding:14px 16px;border:1px solid #dce6ed;border-radius:12px;background:linear-gradient(145deg,#fbfdff,#f5f9fb);box-shadow:0 6px 18px rgba(37,75,95,.06)}.contract-selections label>span{font-weight:700;color:#355468;letter-spacing:.02em}.contract-picker{height:46px!important;margin-top:10px!important;cursor:pointer;transition:border-color .2s,box-shadow .2s}.contract-picker:hover,.contract-picker:focus{border-color:#4c9ab1!important;box-shadow:0 0 0 3px rgba(76,154,177,.12);outline:0}.contract-selections select option{padding:8px}.formal-contract section:nth-of-type(4) p{color:#6f7d87;font-size:12px}
.contract-selections select[multiple].contract-picker{height:132px!important;padding:8px!important;background:#fff!important;line-height:1.8}.selection-hint{display:block;margin-top:7px;color:#84939d;font-size:11px}.contract-selections select[multiple].contract-picker option:checked{background:linear-gradient(90deg,#e7f5f8,#d8eef2);color:#245d70;font-weight:600}
.formal-contract{max-width:980px;margin:0 auto;border:1px solid #c9c9c9;box-shadow:0 10px 24px rgba(0,0,0,.06)}.formal-contract section{padding:0 4px}.formal-contract section p{letter-spacing:.015em;text-align:justify}.formal-contract h3{font-weight:700;letter-spacing:.04em}.contract-heading p{letter-spacing:.02em}.contract-sign{padding-bottom:16px}.contract-sign>div{position:relative;padding:8px 0}.contract-actions{background:#fff;position:sticky;bottom:0}
.contract-code-label{margin-bottom:10px;color:#666;font:600 10px/1.2 ui-monospace,Consolas,monospace;letter-spacing:.28em}.contract-subtitle{margin-top:-2px;color:#333;font-size:13px;letter-spacing:.12em}.contract-title-rule{display:flex;align-items:center;gap:12px;width:270px;margin:16px auto 10px;color:#777;font-size:11px;letter-spacing:.16em}.contract-title-rule i{height:1px;flex:1;background:#444}.contract-heading-meta{display:flex;justify-content:space-between;gap:20px;margin-top:14px;padding-top:10px;border-top:1px solid #777;color:#333;font-size:12px;text-align:left}.contract-heading-meta>span{display:flex;align-items:baseline;gap:4px;min-width:0}.contract-heading-meta input{width:210px;min-width:0}.contract-heading-meta b{font-weight:500}.formal-contract section:first-of-type{margin-top:26px}.formal-contract section:not(:first-of-type){break-inside:avoid}.formal-contract section h3{display:flex;align-items:center;gap:10px}.formal-contract section h3::after{content:"";height:1px;flex:1;background:#c8c8c8}.formal-contract .contract-selections{margin-top:12px}.formal-contract .selection-hint{font-family:var(--font-body)}
.formal-contract section{border-top:0!important}.formal-contract section h3::after{display:none}
.picker-list{display:grid;gap:6px;height:132px!important;overflow:auto;scrollbar-width:none;padding:8px!important;border:1px solid #d9e1e8!important;border-radius:8px!important;background:#fff!important}
.picker-list::-webkit-scrollbar{display:none}.picker-option{display:flex!important;flex-direction:row!important;align-items:center;gap:9px;padding:8px 10px;border:1px solid transparent;border-radius:7px;background:#fff;cursor:pointer;color:#263f4c!important;transition:background .18s,border-color .18s}.picker-option:hover{background:#f2f8fa;border-color:#c5dfe6}.picker-option:has(input:checked){background:#e8f5f7;border-color:#8fc5d0;color:#20586b!important}.picker-option input{width:15px;height:15px;min-height:auto!important;accent-color:#37879a}.picker-option span{min-width:0;font-size:12px;line-height:1.35}.picker-option small{display:block;margin-top:2px;color:#81919b;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.picker-empty{padding:24px 8px!important;margin:0!important;text-align:center;color:#8a99a2!important;font-size:12px!important;text-indent:0!important}
</style>
