<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Activity, Power, PowerOff, RefreshCw, Zap } from '@lucide/vue'
import { useAlertRef } from '@/composables/useAppAlert'
import { useRoute, useRouter } from 'vue-router'
import AppDataTable from '@/components/app/AppDataTable.vue'
import AppDialog from '@/components/app/AppDialog.vue'
import AppDrawer from '@/components/app/AppDrawer.vue'
import FilterBar from '@/components/app/FilterBar.vue'
import StatusTag from '@/components/app/StatusTag.vue'
import { access, replayAccessRawMessage, sendCommand } from '@/api/platform'
import { unwrapRemote } from '@/api/http'
import type { RecordRow } from '@/types/domain'
import { accessLabel, onlineLabel } from '@/utils/enumLabels'

const route = useRoute()
const router = useRouter()
const mode = computed(() => String(route.meta.kind))
const title = computed(() => String(route.meta.title))
const rows = ref<RecordRow[]>([])
const payload = ref<RecordRow>({})
const keyword = ref('')
const gatewayId = ref('')
const targetId = ref('')
const commandStatus = ref('')
const onlineStatus = ref('')
const loading = ref(false)
const error = useAlertRef()
const selected = ref<RecordRow | null>(null)
const dialog = ref(false)
const command = reactive<{ targetId: string; commandType: string; commandPayloadText: string }>({ targetId: '', commandType: '', commandPayloadText: '{}' })
const controlBusy = ref('')
const quickCommands = [
  { key: 'close', label: '合闸', icon: Power, commandType: 'DEVICE_COMMAND', payload: { commandCode: 'BREAKER_CLOSE' } },
  { key: 'open', label: '分闸', icon: PowerOff, commandType: 'DEVICE_COMMAND', payload: { commandCode: 'BREAKER_OPEN' } },
  { key: 'read', label: '立即读取', icon: Zap, commandType: 'READ_NOW', payload: {} },
] as const

const columns = computed(() => mode.value === 'access' ? [{ key: 'gatewaySn', label: '网关编号' }, { key: 'topicGatewayId', label: '接入标识' }, { key: 'status', label: '在线状态', format: onlineLabel }, { key: 'lastSeenTime', label: '最后在线' }] : [{ key: 'target_sn', label: '目标编号' }, { key: 'command_type', label: '指令类型' }, { key: 'request_username', label: '发起人' }, { key: 'request_time', label: '发起时间' }, { key: 'response_time', label: '响应时间' }, { key: 'status', label: '执行状态' }, { key: 'fail_reason', label: '失败原因' }])
const formatAccessStatus = (value: unknown) => accessLabel(value)
const queryText = (value: unknown) => Array.isArray(value) ? String(value[0] ?? '') : String(value ?? '')
const syncQueryFilters = () => { gatewayId.value = queryText(route.query.gatewayId); targetId.value = queryText(route.query.targetId || route.query.deviceId) }
const commandTypes = computed(() => Array.isArray(payload.value.types) ? payload.value.types as unknown as RecordRow[] : [])
const commandTargets = computed(() => payload.value.targets as RecordRow || {})
const gateways = computed(() => Array.isArray(commandTargets.value.gateways) ? commandTargets.value.gateways as unknown as RecordRow[] : [])
const devices = computed(() => Array.isArray(commandTargets.value.devices) ? commandTargets.value.devices as unknown as RecordRow[] : [])
const selectedControlDevice = computed(() => devices.value.find((device) => String(device.id) === String(targetId.value)) || devices.value[0] || null)
const selectedGateway = computed(() => gateways.value.find((gateway) => String(gateway.id) === String(selectedControlDevice.value?.gateway_id || selectedControlDevice.value?.gatewayId || gatewayId.value)) || null)
const controlStatus = computed(() => selectedControlDevice.value ? onlineLabel(selectedControlDevice.value.status || selectedControlDevice.value.online_status || selectedControlDevice.value.onlineStatus || 'UNKNOWN') : '未选择')
const rawMessages = computed(() => Array.isArray(payload.value.raw) ? payload.value.raw as unknown as RecordRow[] : [])
const discoveredDevices = computed(() => Array.isArray(payload.value.discovered) ? payload.value.discovered as unknown as RecordRow[] : [])
const onlineGatewayCount = computed(() => rows.value.filter((row) => String(row.status).toUpperCase() === 'ONLINE').length)
const pendingDiscoveryCount = computed(() => discoveredDevices.value.filter((row) => String(row.discoveryStatus).toUpperCase() !== 'BOUND').length)
const invalidRawCount = computed(() => rawMessages.value.filter((row) => ['INVALID', 'MQ_FAILED'].includes(String(row.status).toUpperCase())).length)
const rawMessageColumns = [{ key: 'gatewaySn', label: '网关编号' }, { key: 'receiveTime', label: '接收时间' }, { key: 'messageType', label: '报文类型' }, { key: 'status', label: '解析状态' }, { key: 'failReason', label: '失败原因' }]
const discoveryColumns = [{ key: 'deviceSn', label: '发现设备 SN' }, { key: 'gatewayId', label: '网关 ID' }, { key: 'protocolAddr', label: '协议地址' }, { key: 'seenCount', label: '上报次数' }, { key: 'lastSeenTime', label: '最近发现' }, { key: 'discoveryStatus', label: '接入状态' }, { key: 'failReason', label: '待处理原因' }]
async function load() { loading.value = true; error.value = ''; try { if (mode.value === 'access') { const [gatewaysResponse, raw, discovered] = await Promise.all([access('gateways/status'), access('raw-messages'), access('discovered-devices')]); const gatewayData = unwrapRemote(gatewaysResponse) as unknown as RecordRow[]; payload.value = { gateways: gatewayData, raw: unwrapRemote(raw), discovered: unwrapRemote(discovered) }; rows.value = (Array.isArray(gatewayData) ? gatewayData : []).filter((row) => !onlineStatus.value || String(row.status) === onlineStatus.value); return } if (mode.value === 'control') { const [targets, types] = await Promise.all([access('command-targets'), access('command-types')]); payload.value = { targets: unwrapRemote(targets), types: unwrapRemote(types) }; const defaultDevice = devices.value[0]; if (!targetId.value && defaultDevice?.id) targetId.value = String(defaultDevice.id); const commands = await access('commands/page', { pageNum: 1, pageSize: 30, keyword: keyword.value || undefined, gatewayId: gatewayId.value || undefined, targetId: targetId.value || undefined, status: commandStatus.value || undefined }); const page = commands as unknown as { records?: RecordRow[] }; rows.value = page.records || []; return } const [page, targets] = await Promise.all([access('commands/page', { pageNum: 1, pageSize: 50, keyword: keyword.value, gatewayId: gatewayId.value || undefined, targetId: targetId.value || undefined, status: commandStatus.value || undefined }), access('command-targets')]); payload.value = { targets: unwrapRemote(targets) }; rows.value = (page as unknown as { records?: RecordRow[] }).records || [] } catch (e) { error.value = e instanceof Error ? e.message : '接入服务读取失败'; rows.value = [] } finally { loading.value = false } }
function onboard(row: RecordRow) { router.push({ path: '/device-archive/devices', query: { discoveryId: String(row.id || ''), deviceSn: String(row.deviceSn || ''), gatewayId: String(row.gatewayId || ''), protocolAddr: String(row.protocolAddr || ''), rawLogId: String(row.latestRawLogId || '') } }) }
async function openRawMessage(row: RecordRow) { try { selected.value = unwrapRemote(await access(`raw-messages/${row.id}`)) as RecordRow } catch (e) { error.value = e instanceof Error ? e.message : '原始报文详情读取失败' } }
async function replayRawMessage() { if (!selected.value?.id) return; try { await replayAccessRawMessage(selected.value.id); await load() } catch (e) { error.value = e instanceof Error ? e.message : '原始报文重放失败' } }
function openCommand() { command.targetId = ''; command.commandType = ''; command.commandPayloadText = '{}'; dialog.value = true }
async function submitCommand() { try { const result = await sendCommand({ targetId: Number(command.targetId), commandType: command.commandType, commandPayload: JSON.parse(String(command.commandPayloadText)) }); selected.value = result; dialog.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '指令下发失败' } }
async function sendQuickCommand(item: typeof quickCommands[number]) { const device = selectedControlDevice.value; if (!device?.id) { error.value = '请先选择设备'; return } controlBusy.value = item.key; error.value = ''; try { const result = await sendCommand({ targetId: Number(device.id), commandType: item.commandType, commandPayload: item.payload }); selected.value = result; await load() } catch (e) { error.value = e instanceof Error ? e.message : `${item.label}指令下发失败` } finally { controlBusy.value = '' } }
async function refreshSelectedCommand() { const id = selected.value?.commandId || selected.value?.command_id || selected.value?.id; if (!id) return; try { selected.value = unwrapRemote(await access(`commands/${id}`)) as RecordRow } catch (e) { error.value = e instanceof Error ? e.message : '指令状态读取失败' } }
watch(() => route.fullPath, () => { syncQueryFilters(); void load() }); onMounted(() => { syncQueryFilters(); void load() })
</script>
<template>
  <section class="view-page"><header class="view-head"><div><p class="eyebrow">DEVICE OPERATIONS</p><h1>{{ title }}</h1></div><div class="head-actions"><button v-if="mode === 'control'" class="quiet" @click="openCommand">高级指令</button><button class="quiet" title="手动刷新" aria-label="手动刷新" @click="load"><RefreshCw :size="15" />刷新</button></div></header>
    <template v-if="mode === 'access'"><article class="filter-card"><div class="filter-row"><label class="field"><span>网关状态</span><AppSelect v-model="onlineStatus"><option value="">全部</option><option value="ONLINE">在线</option><option value="OFFLINE">离线</option></AppSelect></label><div class="filter-actions"><button class="btn-primary" @click="load">查询</button></div></div></article><div class="access-diagnostic-grid"><article><small>在线网关</small><strong>{{ onlineGatewayCount }} / {{ rows.length }}</strong><span>以最近心跳判断</span></article><article><small>待登记设备</small><strong>{{ pendingDiscoveryCount }}</strong><span>需要完成设备档案绑定</span></article><article><small>异常报文</small><strong>{{ invalidRawCount }}</strong><span>解析失败或转发失败</span></article></div><article class="panel access-health-panel"><div class="panel-head"><div><h3>接入链路健康度</h3><small>网关心跳、原始报文和设备发现的同屏诊断</small></div><button class="quiet" title="刷新诊断" aria-label="刷新诊断" @click="load"><RefreshCw :size="14" /></button></div><div class="access-gateway-list"><div v-for="gateway in rows" :key="String(gateway.id || gateway.gatewaySn)" class="access-gateway-row"><span class="access-health-dot" :class="String(gateway.status).toUpperCase() === 'ONLINE' ? 'online' : 'offline'"></span><span><b>{{ gateway.gatewayName || gateway.gatewaySn || '未命名网关' }}</b><small>{{ gateway.gatewaySn || '-' }} · 最近在线 {{ gateway.lastSeenTime || '-' }}</small></span><strong>{{ onlineLabel(gateway.status) }}</strong></div><p v-if="!rows.length" class="muted-copy">当前授权范围暂无网关状态。</p></div></article><AppDataTable title="待接入设备" :columns="discoveryColumns" :rows="discoveredDevices" :loading="loading" :error="error" empty-text="暂无待接入设备。"><template #cell-discoveryStatus="{ value }"><span class="tag" :class="String(value) === 'BOUND' ? 'success' : 'warn'">{{ formatAccessStatus(value) }}</span></template><template #actions="{ row }"><button v-if="String(row.discoveryStatus) !== 'BOUND'" class="link-btn" @click="onboard(row)">进入设备登记</button><button v-else class="link-btn" @click="selected = row">查看绑定</button></template></AppDataTable><AppDataTable title="原始报文记录" :columns="rawMessageColumns" :rows="rawMessages" :loading="loading" :error="error" empty-text="当前授权范围暂无原始报文。"><template #cell-status="{ value }"><span class="tag" :class="String(value) === 'FORWARDED' ? 'success' : String(value) === 'INVALID' || String(value) === 'MQ_FAILED' ? 'danger' : 'warn'">{{ formatAccessStatus(value || 'RECEIVED') }}</span></template><template #actions="{ row }"><button class="link-btn" @click="openRawMessage(row)">查看详情</button></template></AppDataTable></template>
    <template v-else-if="mode === 'control'"><div class="control-console"><article class="panel control-panel"><div class="panel-head"><div><h3>设备控制</h3><small>{{ selectedControlDevice?.device_sn || selectedControlDevice?.deviceSn || '请选择设备' }}</small></div><span class="control-state"><span class="access-health-dot" :class="String(selectedControlDevice?.status).toUpperCase() === 'ONLINE' ? 'online' : 'offline'"></span>{{ controlStatus }}</span></div><label class="dialog-field control-select"><span>目标设备</span><AppSelect v-model="targetId"><option v-for="device in devices" :key="String(device.id)" :value="String(device.id)">{{ device.device_name || device.deviceName || device.device_sn || device.deviceSn }}</option></AppSelect></label><div class="control-meta"><span><b>网关</b>{{ selectedGateway?.gateway_name || selectedGateway?.gatewayName || selectedGateway?.gateway_sn || selectedGateway?.gatewaySn || selectedControlDevice?.gateway_id || '-' }}</span><span><b>设备编号</b>{{ selectedControlDevice?.device_sn || selectedControlDevice?.deviceSn || '-' }}</span><span><b>控制寄存器</b>0x2200</span></div><div class="quick-command-grid"><button v-for="item in quickCommands" :key="item.key" :class="item.key === 'close' ? 'primary command-btn' : 'quiet command-btn'" :disabled="!selectedControlDevice?.id || Boolean(controlBusy)" @click="sendQuickCommand(item)"><component :is="item.icon" :size="16" />{{ controlBusy === item.key ? '下发中' : item.label }}</button></div></article><article class="panel command-panel"><div class="panel-head"><div><h3>指令追踪</h3><small>控制台下发、网关响应和失败原因</small></div><Activity :size="18" /></div><div class="command-type-list"><span v-for="item in commandTypes" :key="String(item.commandType)">{{ item.label || item.commandType }}</span></div></article></div></template>
    <FilterBar v-if="mode === 'commands' || mode === 'control'" v-model:keyword="keyword" :busy="loading" placeholder="目标编号或指令类型" @query="load" @reset="() => { keyword = ''; gatewayId = ''; targetId = ''; commandStatus = ''; load() }"><label class="field inline"><span>网关</span><AppSelect v-model="gatewayId"><option value="">全部网关</option><option v-for="gateway in gateways" :key="String(gateway.id)" :value="String(gateway.id)">{{ gateway.gateway_name || gateway.gateway_sn }}</option></AppSelect></label><label class="field inline"><span>设备</span><AppSelect v-model="targetId"><option value="">全部设备</option><option v-for="device in devices" :key="String(device.id)" :value="String(device.id)">{{ device.device_name || device.device_sn }}</option></AppSelect></label><label class="field inline"><span>执行状态</span><AppSelect v-model="commandStatus"><option value="">全部</option><option value="0">待下发</option><option value="1">已发布</option><option value="2">成功</option><option value="3">失败</option><option value="4">超时</option></AppSelect></label></FilterBar>
    <AppDataTable :columns="columns" :rows="rows" :loading="loading" :error="error" @refresh="load" @detail="(row) => selected = row"><template #cell-status="{ value }"><StatusTag v-if="mode !== 'access'" domain="command" :value="value" /><span v-else class="tag" :class="String(value) === 'ONLINE' ? 'success' : 'muted'">{{ onlineLabel(value) }}</span></template></AppDataTable>
    <AppDrawer :open="Boolean(selected)" title="指令 / 接入详情" @update:open="(open) => { if (!open) selected = null }"><div class="head-actions"><button v-if="mode !== 'access'" class="quiet" @click="refreshSelectedCommand"><RefreshCw :size="14" />刷新指令状态</button><button v-if="mode === 'access' && selected?.payload" class="primary" @click="replayRawMessage">重放此报文</button></div><pre>{{ JSON.stringify(selected, null, 2) }}</pre></AppDrawer>
    <AppDialog v-model:open="dialog" title="下发设备指令" @submit="submitCommand"><div class="dialog-fields"><label class="dialog-field"><span>目标设备*</span><AppSelect v-model="command.targetId"><option value="">请选择设备</option><option v-for="device in devices" :key="String(device.id)" :value="String(device.id)">{{ device.device_name }} · {{ device.device_sn }}</option></AppSelect></label><label class="dialog-field"><span>指令类型*</span><AppSelect v-model="command.commandType"><option value="">请选择指令</option><option v-for="item in commandTypes" :key="String(item.commandType)" :value="String(item.commandType)">{{ item.label }}</option></AppSelect></label><label class="dialog-field full"><span>指令参数 JSON*</span><textarea v-model="command.commandPayloadText" spellcheck="false"></textarea></label></div></AppDialog>
  </section>
</template>
<style scoped>
.access-diagnostic-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.access-diagnostic-grid article{display:grid;gap:5px;padding:14px;border:1px solid var(--border);border-radius:8px;background:#fff}.access-diagnostic-grid small,.access-diagnostic-grid span,.access-gateway-row small{color:var(--muted);font-size:11px}.access-diagnostic-grid strong{color:#24415f;font-size:22px}.access-health-panel{padding:14px}.access-gateway-list{display:grid;gap:0;margin-top:10px;border-top:1px solid var(--line-soft)}.access-gateway-row{display:flex;align-items:center;gap:9px;padding:10px 0;border-bottom:1px solid var(--line-soft)}.access-gateway-row>span:nth-child(2){min-width:0;flex:1}.access-gateway-row b,.access-gateway-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.access-gateway-row small{margin-top:3px}.access-gateway-row strong{font-size:11px;color:#17804f}.access-health-dot{width:8px;height:8px;flex:none;border-radius:50%;background:#a3afbb}.access-health-dot.online{background:#1bb37d;box-shadow:0 0 0 3px #e5f6ef}.access-health-dot.offline{background:#d95d48;box-shadow:0 0 0 3px #fff0ec}@media(max-width:700px){.access-diagnostic-grid{grid-template-columns:1fr}}
.control-console{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(260px,.7fr);gap:12px}.control-panel,.command-panel{padding:14px}.control-state{display:inline-flex;align-items:center;gap:8px;color:#31465a;font-size:12px;font-weight:700}.control-select{margin-top:12px}.control-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:12px 0}.control-meta span{min-width:0;padding:10px;border:1px solid var(--line-soft);border-radius:8px;background:#f8fafc;color:#34475b;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.control-meta b{display:block;margin-bottom:4px;color:var(--muted);font-size:10px;font-weight:600}.quick-command-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.command-btn{width:100%;justify-content:center;gap:6px}.command-type-list{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.command-type-list span{padding:5px 9px;border:1px solid #d9e5f0;border-radius:999px;background:#f8fbff;color:#38536d;font-size:11px}@media(max-width:900px){.control-console{grid-template-columns:1fr}.control-meta,.quick-command-grid{grid-template-columns:1fr}}
</style>
