<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import AppDataTable from '@/components/app/AppDataTable.vue'
import AppDialog from '@/components/app/AppDialog.vue'
import AppDrawer from '@/components/app/AppDrawer.vue'
import FilterBar from '@/components/app/FilterBar.vue'
import StatusTag from '@/components/app/StatusTag.vue'
import { resourceSchemas } from '@/config/resourceSchemas'
import { createResource, deviceProfile, deviceTypePoints, listResource, parsePoints, removeResource, saveDeviceTypePoints, updateResource } from '@/api/platform'
import type { RecordRow } from '@/types/domain'
import { useSessionStore } from '@/stores/session'

const route = useRoute(); const session = useSessionStore(); const schema = computed(() => resourceSchemas[String(route.meta.resource || '').replace('billing:', '')])
const rows = ref<RecordRow[]>([]); const selected = ref<RecordRow | null>(null); const keyword = ref(''); const orgId = ref(''); const gatewayId = ref(''); const deviceTypeId = ref(''); const accountId = ref(''); const pageNum = ref(1); const total = ref(0); const loading = ref(false); const error = ref(''); const dialog = ref(false); const saving = ref(false); const editingId = ref<unknown>(null); const form = reactive<RecordRow>({}); const parseDialog = ref(false); const parseForm = reactive<RecordRow>({ deviceTypeId: '', samplePayload: '{}' }); const batchDialog = ref(false); const batchTypeId = ref<unknown>(null); const batchText = ref('{\n  "definitions": [],\n  "mappings": []\n}'); const orgOptions = ref<RecordRow[]>([]); const gatewayOptions = ref<RecordRow[]>([]); const typeOptions = ref<RecordRow[]>([]); const accountOptions = ref<RecordRow[]>([])
const pageSize = 20; const canAdd = computed(() => session.can(schema.value.area === 'archive' ? 'archive:add' : 'billing:add')); const canEdit = computed(() => session.can(schema.value.area === 'archive' ? 'archive:edit' : 'billing:edit')); const canDelete = computed(() => session.can(schema.value.area === 'archive' ? 'archive:delete' : 'billing:delete'))
function copy(target: RecordRow, source: RecordRow) { Object.keys(target).forEach((key) => delete target[key]); Object.assign(target, source) }
const showOrgFilter = computed(() => ['gateways', 'devices', 'accounts'].includes(schema.value.resource)); const showGatewayFilter = computed(() => schema.value.resource === 'devices'); const showTypeFilter = computed(() => ['devices', 'point-definitions', 'point-mappings'].includes(schema.value.resource)); const showAccountFilter = computed(() => ['rules'].includes(schema.value.resource))
async function load() { loading.value = true; error.value = ''; try { const page = await listResource(schema.value.area, schema.value.resource, { pageNum: pageNum.value, pageSize, keyword: keyword.value, orgId: orgId.value || undefined, gatewayId: gatewayId.value || undefined, deviceTypeId: deviceTypeId.value || undefined, accountId: accountId.value || undefined }); rows.value = page.records; total.value = page.total } catch (e) { error.value = e instanceof Error ? e.message : '读取失败'; rows.value = []; total.value = 0 } finally { loading.value = false } }
async function loadLookups() { try { if (session.can('archive:list')) { const [orgs, gateways, types] = await Promise.all([listResource('archive', 'orgs', { pageSize: 200 }), listResource('archive', 'gateways', { pageSize: 200 }), listResource('archive', 'device-types', { pageSize: 200 })]); orgOptions.value = orgs.records; gatewayOptions.value = gateways.records; typeOptions.value = types.records } if (session.can('billing:list')) accountOptions.value = (await listResource('billing', 'accounts', { pageSize: 200 })).records } catch { /* lookups are optional; primary table still reports its own request failure */ } }
function openCreate() { editingId.value = null; copy(form, structuredClone(schema.value.defaults)); dialog.value = true }
function openEdit(row: RecordRow) { editingId.value = row.id; copy(form, Object.fromEntries(schema.value.fields.map((field) => [field.key, row[field.key] ?? '']))); dialog.value = true }
async function save() { saving.value = true; try { const body = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')) as RecordRow; if (editingId.value) await updateResource(schema.value.area, schema.value.resource, editingId.value, body); else await createResource(schema.value.area, schema.value.resource, body); dialog.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } finally { saving.value = false } }
async function detail(row: RecordRow) { selected.value = row; if (schema.value.resource !== 'devices') return; try { selected.value = await deviceProfile(row.id) } catch (e) { error.value = e instanceof Error ? e.message : '详情读取失败' } }
async function remove(row: RecordRow) { if (!confirm(`确定删除「${String(row.id)}」吗？`)) return; try { await removeResource(schema.value.area, schema.value.resource, row.id); await load() } catch (e) { error.value = e instanceof Error ? e.message : '删除失败' } }
async function runParseTest() { try { selected.value = await parsePoints({ deviceTypeId: Number(parseForm.deviceTypeId), samplePayload: JSON.parse(String(parseForm.samplePayload)) }); parseDialog.value = false } catch (e) { error.value = e instanceof Error ? e.message : '解析测试失败' } }
async function openBatch(row: RecordRow) { try { batchTypeId.value = row.id; batchText.value = JSON.stringify(await deviceTypePoints(row.id), null, 2); batchDialog.value = true } catch (e) { error.value = e instanceof Error ? e.message : '测点配置读取失败' } }
async function saveBatch() { if (!batchTypeId.value) return; try { await saveDeviceTypePoints(batchTypeId.value, JSON.parse(batchText.value) as RecordRow); batchDialog.value = false } catch (e) { error.value = e instanceof Error ? e.message : '批量测点保存失败' } }
function reset() { keyword.value = ''; orgId.value = ''; gatewayId.value = ''; deviceTypeId.value = ''; accountId.value = ''; pageNum.value = 1; load() }
watch(() => route.fullPath, () => { reset(); loadLookups() }); onMounted(() => { load(); loadLookups() })
</script>
<template>
  <section v-if="schema" class="view-page"><header class="view-head"><div><p class="eyebrow">{{ schema.area.toUpperCase() }} CONFIGURATION</p><h1>{{ schema.title }}</h1><p>{{ schema.description }}</p></div><div class="head-actions"><button v-if="schema.resource === 'point-mappings' && canEdit" class="quiet" @click="parseDialog = true">解析测试</button><button v-if="canAdd" class="primary" @click="openCreate">新增{{ schema.title }}</button><button class="quiet" @click="load">刷新</button></div></header>
    <FilterBar v-model:keyword="keyword" :busy="loading" @query="load" @reset="reset"><label v-if="showOrgFilter" class="field inline"><span>所属组织</span><select v-model="orgId"><option value="">全部组织</option><option v-for="org in orgOptions" :key="String(org.id)" :value="String(org.id)">{{ org.org_name }}</option></select></label><label v-if="showGatewayFilter" class="field inline"><span>接入网关</span><select v-model="gatewayId"><option value="">全部网关</option><option v-for="gateway in gatewayOptions" :key="String(gateway.id)" :value="String(gateway.id)">{{ gateway.gateway_name || gateway.gateway_sn }}</option></select></label><label v-if="showTypeFilter" class="field inline"><span>设备类型</span><select v-model="deviceTypeId"><option value="">全部类型</option><option v-for="type in typeOptions" :key="String(type.id)" :value="String(type.id)">{{ type.type_name || type.type_code }}</option></select></label><label v-if="showAccountFilter" class="field inline"><span>计费账户</span><select v-model="accountId"><option value="">全部账户</option><option v-for="account in accountOptions" :key="String(account.id)" :value="String(account.id)">{{ account.account_name }}</option></select></label></FilterBar>
    <AppDataTable :columns="schema.columns" :rows="rows" :loading="loading" :error="error" @refresh="load" @detail="detail"><template #cell-online_status="{ value }"><StatusTag domain="online" :value="value" /></template><template #cell-status="{ value }"><StatusTag domain="online" :value="value" /></template><template #actions="{ row }"><button class="link-btn" @click="detail(row)">详情</button><button v-if="schema.resource === 'device-types' && canEdit" class="link-btn" @click="openBatch(row)">配置测点</button><button v-if="canEdit" class="link-btn" @click="openEdit(row)">编辑</button><button v-if="canDelete" class="link-btn danger-text" @click="remove(row)">删除</button></template></AppDataTable>
    <div v-if="total > pageSize" class="pagination"><button class="quiet" :disabled="pageNum <= 1" @click="pageNum--; load()">上一页</button><span>第 {{ pageNum }} 页，共 {{ total }} 条</span><button class="quiet" :disabled="rows.length < pageSize" @click="pageNum++; load()">下一页</button></div>
    <AppDrawer :open="Boolean(selected)" title="档案详情" @update:open="(open) => { if (!open) selected = null }"><pre>{{ JSON.stringify(selected, null, 2) }}</pre></AppDrawer>
    <AppDialog v-model:open="dialog" :title="editingId ? `编辑${schema.title}` : `新增${schema.title}`" :description="'字段与 Platform TableRegistry 白名单一致。'" :saving="saving" @submit="save"><div class="dialog-fields"><label v-for="field in schema.fields" :key="field.key" class="dialog-field" :class="{ full: field.type === 'textarea' }"><span>{{ field.label }}<i v-if="field.required">*</i></span><textarea v-if="field.type === 'textarea'" v-model="form[field.key]"></textarea><select v-else-if="field.type === 'select'" v-model="form[field.key]"><option v-for="option in field.options" :key="String(option.value)" :value="option.value">{{ option.label }}</option></select><input v-else v-model="form[field.key]" :type="field.type || 'text'" :required="field.required"></label></div></AppDialog>
    <AppDialog v-model:open="parseDialog" title="协议映射解析测试" description="提交 deviceTypeId 与 JSON 示例报文；Platform 按已配置 source_path 返回解析结果。" @submit="runParseTest"><div class="dialog-fields"><label class="dialog-field"><span>设备类型 ID</span><input v-model="parseForm.deviceTypeId" type="number"></label><label class="dialog-field full"><span>JSON 示例报文</span><textarea v-model="parseForm.samplePayload" spellcheck="false"></textarea></label></div></AppDialog>
    <AppDialog v-model:open="batchDialog" title="批量配置设备类型测点" description="该专用接口的请求体固定为 definitions 与 mappings 两个数组。" @submit="saveBatch"><div class="dialog-fields"><label class="dialog-field full"><span>批量配置 JSON</span><textarea v-model="batchText" spellcheck="false"></textarea></label></div></AppDialog>
  </section>
</template>
