<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import AppDataTable from '@/components/app/AppDataTable.vue'
import AppDialog from '@/components/app/AppDialog.vue'
import AppDrawer from '@/components/app/AppDrawer.vue'
import FilterBar from '@/components/app/FilterBar.vue'
import { audit, rbac } from '@/api/platform'
import type { RecordRow } from '@/types/domain'
import { useSessionStore } from '@/stores/session'

const route = useRoute(); const session = useSessionStore(); const mode = computed(() => String(route.meta.kind)); const title = computed(() => String(route.meta.title)); const rows = ref<RecordRow[]>([]); const relations = ref<RecordRow>({}); const selected = ref<RecordRow | null>(null); const keyword = ref(''); const loading = ref(false); const error = ref(''); const dialog = ref(false); const editingId = ref<unknown>(null); const form = reactive<RecordRow>({}); const relationDialog = ref(false); const relationTitle = ref(''); const relationTargetId = ref<unknown>(null); const relationMode = ref<'password' | 'roles' | 'permissions' | 'scopes'>('roles'); const relationText = ref('')
const configuration = computed(() => ({ users: { endpoint: 'users', permission: 'system:user', columns: [{ key: 'username', label: '登录名' }, { key: 'nickname', label: '姓名' }, { key: 'orgId', label: '默认组织' }, { key: 'status', label: '状态' }], fields: ['username', 'nickname', 'password', 'orgId', 'phone', 'email', 'status'], defaults: { username: '', nickname: '', password: '', orgId: '', phone: '', email: '', status: 1 } }, roles: { endpoint: 'roles', permission: 'system:role', columns: [{ key: 'roleCode', label: '角色编码' }, { key: 'roleName', label: '角色名称' }, { key: 'dataScope', label: '数据范围' }, { key: 'status', label: '状态' }], fields: ['roleCode', 'roleName', 'dataScope', 'remark', 'status'], defaults: { roleCode: '', roleName: '', dataScope: 1, remark: '', status: 1 } }, permissions: { endpoint: 'permissions', permission: 'system:permission', columns: [{ key: 'permCode', label: '权限码' }, { key: 'permName', label: '权限名称' }, { key: 'permType', label: '类型' }, { key: 'parentId', label: '上级 ID' }, { key: 'sort', label: '排序' }], fields: ['permCode', 'permName', 'permType', 'parentId', 'routePath', 'componentPath', 'icon', 'sort', 'status'], defaults: { permCode: '', permName: '', permType: 3, parentId: 0, routePath: '', componentPath: '', icon: '', sort: 0, status: 1 } } } as Record<string, { endpoint: string; permission: string; columns: Array<{ key: string; label: string }>; fields: string[]; defaults: RecordRow }>)[mode.value])
const canAdd = computed(() => configuration.value && session.can(`${configuration.value.permission}:add`)); const canEdit = computed(() => configuration.value && session.can(`${configuration.value.permission}:edit`)); const canDelete = computed(() => configuration.value && session.can(`${configuration.value.permission}:delete`))
async function load() { loading.value = true; error.value = ''; try { if (mode.value === 'audit') { const page = await audit('operation-logs', { pageNum: 1, pageSize: 100, keyword: keyword.value }); rows.value = page.records; return } if (mode.value === 'profile') { const [logs, snapshot] = await Promise.all([audit('my-operations', { pageNum: 1, pageSize: 50, keyword: keyword.value }), session.can('system:role:list') ? rbac('relations') : Promise.resolve({})]); rows.value = logs.records; relations.value = snapshot as RecordRow; return } if (!configuration.value) return; const value = await rbac(`${configuration.value.endpoint}?pageNum=1&pageSize=100&keyword=${encodeURIComponent(keyword.value)}`); rows.value = Array.isArray(value) ? value : (value as { records?: RecordRow[] }).records || [] } catch (e) { error.value = e instanceof Error ? e.message : '系统数据读取失败'; rows.value = [] } finally { loading.value = false } }
function openCreate() { if (!configuration.value) return; editingId.value = null; Object.keys(form).forEach((key) => delete form[key]); Object.assign(form, configuration.value.defaults); dialog.value = true }
function openEdit(row: RecordRow) { if (!configuration.value) return; editingId.value = row.id; Object.keys(form).forEach((key) => delete form[key]); configuration.value.fields.forEach((key) => form[key] = row[key] ?? ''); dialog.value = true }
async function save() { if (!configuration.value) return; try { const init: RequestInit = { method: editingId.value ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }; await rbac(editingId.value ? `${configuration.value.endpoint}/${editingId.value}` : configuration.value.endpoint, init); dialog.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } }
async function remove(row: RecordRow) { if (!configuration.value || !confirm(`确定删除「${String(row.id)}」吗？`)) return; try { await rbac(`${configuration.value.endpoint}/${row.id}`, { method: 'DELETE' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '删除失败' } }
function openRelation(target: RecordRow, modeValue: 'password' | 'roles' | 'permissions' | 'scopes') { relationTargetId.value = target.id; relationMode.value = modeValue; relationTitle.value = ({ password: '重置登录密码', roles: '分配用户角色', permissions: '分配角色权限', scopes: '配置组织数据范围' } as const)[modeValue]; relationText.value = modeValue === 'scopes' ? '1,SELF' : ''; relationDialog.value = true }
async function saveRelation() { if (!relationTargetId.value) return; try { let path = ''; let body: RecordRow = {}; if (relationMode.value === 'password') { path = `users/${relationTargetId.value}/password`; body = { password: relationText.value } } else if (relationMode.value === 'roles') { path = `users/${relationTargetId.value}/roles`; body = { ids: relationText.value.split(',').map((value) => Number(value.trim())).filter(Boolean) } } else if (relationMode.value === 'permissions') { path = `roles/${relationTargetId.value}/permissions`; body = { ids: relationText.value.split(',').map((value) => Number(value.trim())).filter(Boolean) } } else { path = `users/${relationTargetId.value}/org-scopes`; body = { scopes: relationText.value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => { const [orgId, scopeMode] = line.split(','); return { orgId: Number(orgId), scopeMode: (scopeMode || 'SELF').trim() } }) } } await rbac(path, { method: relationMode.value === 'scopes' ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); relationDialog.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '关联配置保存失败' } }
function inputType(field: string) { return ['orgId', 'parentId', 'permType', 'dataScope', 'sort', 'status'].includes(field) ? 'number' : field === 'password' ? 'password' : 'text' }
watch(() => route.fullPath, load); onMounted(load)
</script>
<template>
  <section class="view-page"><header class="view-head"><div><p class="eyebrow">SYSTEM & ACCESS CONTROL</p><h1>{{ title }}</h1><p>{{ mode === 'profile' ? '展示当前会话、可见组织范围和本人操作审计；无角色管理权限时不会请求全局关系快照。' : mode === 'audit' ? '记录配置、处置、支付、指令下发等关键写操作。' : '用户、角色和权限均通过 Platform RBAC 专用接口维护。' }}</p></div><div class="head-actions"><button v-if="canAdd" class="primary" @click="openCreate">新增记录</button><button class="quiet" @click="load">刷新</button></div></header>
    <template v-if="mode === 'profile'"><div class="two-panel"><article class="panel"><div class="panel-head"><h3>当前会话</h3><small>认证与组织范围</small></div><pre>{{ JSON.stringify({ user: session.user, roles: session.roles, permissions: session.permissions, orgScopes: session.orgScopes }, null, 2) }}</pre></article><article class="panel"><div class="panel-head"><h3>RBAC 关系快照</h3><small v-if="!session.can('system:role:list')">当前账号无查看权限</small></div><pre>{{ JSON.stringify(relations, null, 2) }}</pre></article></div></template>
    <FilterBar v-model:keyword="keyword" :busy="loading" @query="load" @reset="() => { keyword = ''; load() }" />
    <AppDataTable :columns="mode === 'audit' || mode === 'profile' ? [{ key: 'username', label: '操作人' }, { key: 'module', label: '模块' }, { key: 'operation', label: '操作' }, { key: 'status', label: '结果' }, { key: 'cost_time', label: '耗时(ms)' }, { key: 'create_time', label: '时间' }] : configuration?.columns || []" :rows="rows" :loading="loading" :error="error" @refresh="load" @detail="(row) => selected = row"><template #actions="{ row }"><button class="link-btn" @click="selected = row">详情</button><button v-if="canEdit" class="link-btn" @click="openEdit(row)">编辑</button><button v-if="mode === 'users' && session.can('system:user:edit')" class="link-btn" @click="openRelation(row, 'roles')">分配角色</button><button v-if="mode === 'users' && session.can('system:user:edit')" class="link-btn" @click="openRelation(row, 'password')">重置密码</button><button v-if="mode === 'users' && session.can('system:user:scope:edit')" class="link-btn" @click="openRelation(row, 'scopes')">组织范围</button><button v-if="mode === 'roles' && session.can('system:role:edit')" class="link-btn" @click="openRelation(row, 'permissions')">分配权限</button><button v-if="canDelete" class="link-btn danger-text" @click="remove(row)">删除</button></template></AppDataTable>
    <AppDrawer :open="Boolean(selected)" title="系统记录详情" @update:open="(open) => { if (!open) selected = null }"><pre>{{ JSON.stringify(selected, null, 2) }}</pre></AppDrawer>
    <AppDialog v-model:open="dialog" :title="editingId ? `编辑${title}` : `新增${title}`" description="请求将发送到 Platform RBAC 专用接口。" @submit="save"><div class="dialog-fields"><label v-for="field in configuration?.fields || []" :key="field" class="dialog-field" :class="{ full: ['remark'].includes(field) }"><span>{{ field }}</span><textarea v-if="field === 'remark'" v-model="form[field]"></textarea><select v-else-if="field === 'permType'" v-model="form[field]"><option :value="1">目录</option><option :value="2">菜单</option><option :value="3">按钮</option></select><input v-else v-model="form[field]" :type="inputType(field)"></label></div></AppDialog>
    <AppDialog v-model:open="relationDialog" :title="relationTitle" description="角色/权限填写 ID 逗号分隔；组织范围每行填写 orgId,SELF 或 orgId,SUBTREE。" @submit="saveRelation"><div class="dialog-fields"><label class="dialog-field full"><span>{{ relationMode === 'password' ? '新密码' : relationMode === 'scopes' ? '组织范围' : 'ID 集合' }}</span><textarea v-if="relationMode === 'scopes'" v-model="relationText" spellcheck="false"></textarea><input v-else v-model="relationText" :type="relationMode === 'password' ? 'password' : 'text'" :placeholder="relationMode === 'password' ? '请输入新密码' : '例如 1,2,3'"></label></div></AppDialog>
  </section>
</template>
