<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Pencil, Plus, RefreshCw, Trash2 } from '@lucide/vue'
import AppConfirmDialog from '@/components/app/AppConfirmDialog.vue'
import AppDataTable, { type TableColumn } from '@/components/app/AppDataTable.vue'
import AppDialog from '@/components/app/AppDialog.vue'
import AppSelect from '@/components/app/AppSelect.vue'
import FilterBar from '@/components/app/FilterBar.vue'
import { createResource, deleteResource, listResource, rbacPage, updateResource } from '@/api/platform'
import { useAlertRef } from '@/composables/useAppAlert'
import type { RecordRow } from '@/types/domain'

const rows=ref<RecordRow[]>([]),users=ref<RecordRow[]>([]),keyword=ref(''),status=ref(''),pageNum=ref(1),total=ref(0),loading=ref(false),saving=ref(false),editingId=ref<unknown>(null),dialog=ref(false),deleting=ref<RecordRow|null>(null),deletingBusy=ref(false),error=useAlertRef()
const form=reactive<Record<string,string>>({tenantCode:'',tenantName:'',tenantType:'ENTERPRISE',contactName:'',contactPhone:'',contactEmail:'',unifiedSocialCreditCode:'',billingAddress:'',ownerUserId:'',status:'ACTIVE',remark:''})
const pageSize=20
const columns:TableColumn[]=[{key:'tenant_code',label:'租户编码'},{key:'tenant_name',label:'租户名称'},{key:'contact_name',label:'联系人'},{key:'contact_phone',label:'联系电话'},{key:'owner_name',label:'归属用户',format:(_,r)=>String(r.owner_name||r.owner_username||'—')},{key:'status',label:'状态',format:v=>String(v)==='ACTIVE'?'启用':'停用'},{key:'update_time',label:'更新时间'}]
function reset(row?:RecordRow){Object.assign(form,{tenantCode:String(row?.tenant_code||row?.tenantCode||''),tenantName:String(row?.tenant_name||row?.tenantName||''),tenantType:String(row?.tenant_type||row?.tenantType||'ENTERPRISE'),contactName:String(row?.contact_name||row?.contactName||''),contactPhone:String(row?.contact_phone||row?.contactPhone||''),contactEmail:String(row?.contact_email||row?.contactEmail||''),unifiedSocialCreditCode:String(row?.unified_social_credit_code||row?.unifiedSocialCreditCode||''),billingAddress:String(row?.billing_address||row?.billingAddress||''),ownerUserId:String(row?.owner_user_id||row?.ownerUserId||''),status:String(row?.status||'ACTIVE'),remark:String(row?.remark||'')})}
async function load(){loading.value=true;error.value='';try{const p=await listResource('billing','tenants',{pageNum:pageNum.value,pageSize,keyword:keyword.value||undefined,status:status.value||undefined});rows.value=p.records||[];total.value=p.total||0}catch(e){error.value=e instanceof Error?e.message:'租户数据加载失败'}finally{loading.value=false}}
async function loadUsers(){try{users.value=(await rbacPage('users',{pageNum:1,pageSize:500})).records||[]}catch(e){error.value=e instanceof Error?e.message:'用户列表加载失败'}}
function openCreate(){editingId.value=null;reset();dialog.value=true}function openEdit(row:RecordRow){editingId.value=row.id;reset(row);dialog.value=true}function query(){pageNum.value=1;load()}
async function save(){if(!form.tenantName||!form.contactName||!form.contactPhone||!form.ownerUserId){error.value='请填写租户名称、联系人、联系电话并选择归属用户';return}saving.value=true;try{if(editingId.value)await updateResource('billing','tenants',editingId.value,form);else await createResource('billing','tenants',form);dialog.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'租户保存失败'}finally{saving.value=false}}
async function confirmDelete(){if(!deleting.value)return;deletingBusy.value=true;try{await deleteResource('billing','tenants',deleting.value.id);deleting.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'租户删除失败'}finally{deletingBusy.value=false}}
onMounted(()=>{load();loadUsers()})
</script>
<template><section class="view-page tenant-page"><header class="view-head"><div><p class="eyebrow">TENANT & USER BINDING</p><h1>租户管理</h1><small>管理员维护结算主体，并将租户归属到具体用户；一个用户可管理多个租户。</small></div></header><FilterBar v-model:keyword="keyword" :busy="loading" @query="query" @reset="()=>{keyword='';status='';query()}"><template #filters><AppSelect v-model="status" @change="query"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></AppSelect></template><template #actions><button class="primary action-with-icon" @click="openCreate"><Plus :size="16"/>新增租户</button><button class="icon-btn" title="刷新" @click="load"><RefreshCw :size="16"/></button></template></FilterBar><AppDataTable :columns="columns" :rows="rows" :loading="loading" :error="error" :total="total" :current-page="pageNum" :page-size="pageSize" empty-text="暂无租户，可由管理员新增并分配归属用户。" @refresh="load" @page-change="next=>{pageNum=next;load()}"><template #actions="{row}"><button class="icon-btn" title="编辑租户" @click="openEdit(row)"><Pencil :size="16"/></button><button class="icon-btn danger-text" title="删除租户" @click="deleting=row"><Trash2 :size="16"/></button></template></AppDataTable><AppDialog v-model:open="dialog" :title="editingId?'编辑租户档案':'新增租户档案'" eyebrow="TENANT MASTER DATA" :saving="saving" @submit="save"><div class="dialog-fields tenant-form"><label class="dialog-field"><span>租户编码</span><input v-model="form.tenantCode" placeholder="不填则自动生成"></label><label class="dialog-field"><span>租户名称</span><input v-model="form.tenantName"></label><label class="dialog-field"><span>归属用户</span><AppSelect v-model="form.ownerUserId"><option value="">请选择用户</option><option v-for="u in users.filter(x=>Number(x.status)===1)" :key="String(u.id)" :value="String(u.id)">{{u.nickname||u.username}}（{{u.username}}）</option></AppSelect></label><label class="dialog-field"><span>状态</span><AppSelect v-model="form.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></AppSelect></label><label class="dialog-field"><span>租户类型</span><AppSelect v-model="form.tenantType"><option value="ENTERPRISE">企业</option><option value="INDIVIDUAL">个人</option></AppSelect></label><label class="dialog-field"><span>统一社会信用代码</span><input v-model="form.unifiedSocialCreditCode"></label><label class="dialog-field"><span>联系人</span><input v-model="form.contactName"></label><label class="dialog-field"><span>联系电话</span><input v-model="form.contactPhone"></label><label class="dialog-field"><span>联系邮箱</span><input v-model="form.contactEmail"></label><label class="dialog-field"><span>开票地址</span><input v-model="form.billingAddress"></label><label class="dialog-field full"><span>备注</span><textarea v-model="form.remark" rows="3"></textarea></label></div></AppDialog><AppConfirmDialog :open="Boolean(deleting)" title="删除租户" message="仅未关联合同和财务账户的租户可以删除；已有业务记录请改为停用。" :loading="deletingBusy" @update:open="v=>{if(!v)deleting=null}" @confirm="confirmDelete"/></section></template>
<style scoped>.tenant-page{display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:14px;min-height:0}.tenant-page :deep(.app-table){min-height:0}.tenant-form{grid-template-columns:repeat(2,minmax(0,1fr))}.tenant-form textarea{width:100%;box-sizing:border-box;resize:vertical}@media(max-width:760px){.tenant-form{grid-template-columns:1fr}}</style>
