<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import AppDataTable from '@/components/app/AppDataTable.vue'
import AppDialog from '@/components/app/AppDialog.vue'
import FilterBar from '@/components/app/FilterBar.vue'
import { contract, contractAction, contracts, listResource, saveContract } from '@/api/platform'
import { useAlertRef } from '@/composables/useAppAlert'
import { useSessionStore } from '@/stores/session'
import type { RecordRow } from '@/types/domain'

const route = useRoute(); const session = useSessionStore(); const error = useAlertRef()
const rows = ref<RecordRow[]>([]); const tenants = ref<RecordRow[]>([]); const spaces = ref<RecordRow[]>([]); const meters = ref<RecordRow[]>([]); const orgs = ref<RecordRow[]>([])
const keyword = ref(''); const status = ref(''); const loading = ref(false); const dialog = ref(false); const saving = ref(false)
const form = reactive({ id: 0, contractNo: '', contractName: '', tenantId: '', orgId: '', startDate: '', endDate: '', settlementDay: 1, depositAmount: '0', remark: '', spaceIds: [] as string[], meterIds: [] as string[] })
const meterFactors = reactive<Record<string, number>>({})
const columns = [{ key: 'contract_no', label: '合同编号' }, { key: 'contract_name', label: '合同名称' }, { key: 'tenant_name', label: '租户' }, { key: 'org_name', label: '园区' }, { key: 'start_date', label: '开始' }, { key: 'end_date', label: '结束' }, { key: 'status', label: '状态' }]
const filteredSpaces = computed(() => spaces.value.filter(item => !form.orgId || String(item.org_id) === form.orgId))
const queryOrg = computed(() => String(route.query.orgId || ''))
function clearMeterFactors() { Object.keys(meterFactors).forEach(key => delete meterFactors[key]) }
function defaultMeterFactor(deviceId: string) { return Number(meters.value.find(item => String(item.id) === deviceId)?.meter_factor || 1) }
function ensureMeterFactor(deviceId: string) { if (form.meterIds.includes(deviceId) && meterFactors[deviceId] == null) meterFactors[deviceId] = defaultMeterFactor(deviceId) }
function reset() { clearMeterFactors(); Object.assign(form, { id: 0, contractNo: `CT-${Date.now()}`, contractName: '', tenantId: '', orgId: queryOrg.value, startDate: new Date().toISOString().slice(0, 10), endDate: '', settlementDay: 1, depositAmount: '0', remark: '', spaceIds: [], meterIds: [] }) }
function payload(): RecordRow { return { contractNo: form.contractNo, contractName: form.contractName, tenantId: Number(form.tenantId), orgId: Number(form.orgId), startDate: form.startDate, endDate: form.endDate, settlementDay: form.settlementDay, depositAmount: form.depositAmount, remark: form.remark, spaces: form.spaceIds.map(spaceId => ({ spaceId: Number(spaceId), startDate: form.startDate })), meters: form.meterIds.map(deviceId => ({ deviceId: Number(deviceId), startDate: form.startDate, meterFactor: Number(meterFactors[deviceId] ?? defaultMeterFactor(deviceId)) })) } }
async function load() { loading.value = true; try { rows.value = (await contracts({ pageNum: 1, pageSize: 200, keyword: keyword.value || undefined, status: status.value || undefined, orgId: queryOrg.value || undefined })).records } catch (e) { error.value = e instanceof Error ? e.message : '读取合同失败' } finally { loading.value = false } }
async function openCreate() { reset(); dialog.value = true }
async function openDetail(row: RecordRow) { try { const data = await contract(row.id); clearMeterFactors(); const contractMeters = Array.isArray(data.meters) ? data.meters as RecordRow[] : []; contractMeters.forEach(item => { meterFactors[String(item.device_id)] = Number(item.meter_factor || 1) }); Object.assign(form, { id: Number(data.id), contractNo: String(data.contract_no), contractName: String(data.contract_name), tenantId: String(data.tenant_id), orgId: String(data.org_id), startDate: String(data.start_date).slice(0,10), endDate: String(data.end_date).slice(0,10), settlementDay: Number(data.settlement_day), depositAmount: String(data.deposit_amount || 0), remark: String(data.remark || ''), spaceIds: Array.isArray(data.spaces) ? (data.spaces as RecordRow[]).map(x => String(x.space_id)) : [], meterIds: contractMeters.map(x => String(x.device_id)) }); dialog.value = true } catch (e) { error.value = e instanceof Error ? e.message : '读取合同详情失败' } }
async function save() { saving.value = true; try { await saveContract(payload(), form.id || undefined); dialog.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '保存合同失败' } finally { saving.value = false } }
async function action(row: RecordRow, type: 'activate' | 'terminate') { try { await contractAction(row.id, type, type === 'terminate' ? { endDate: new Date().toISOString().slice(0,10), remark: '平台终止' } : {}); await load() } catch (e) { error.value = e instanceof Error ? e.message : '合同操作失败' } }
onMounted(async () => { try { const [tenantPage, spacePage, devicePage, orgPage] = await Promise.all([listResource('billing','tenants',{pageSize:500}), listResource('archive','spaces',{pageSize:500}), listResource('archive','devices',{pageSize:500}), listResource('archive','orgs',{pageSize:500})]); tenants.value=tenantPage.records; spaces.value=spacePage.records; meters.value=devicePage.records.filter(x => Number(x.settlement_enabled || 0) === 1); orgs.value=orgPage.records } catch (e) { error.value = e instanceof Error ? e.message : '合同基础档案读取失败' } await load() })
</script>
<template><section class="view-page"><header class="view-head"><div><p class="eyebrow">TENANT · CONTRACT · METER</p><h1>租户合同</h1><p>合同生效后自动创建计费账户，合同绑定的结算表计将成为出账依据。</p></div><button v-if="session.can('billing:contract:edit')" class="btn-primary" @click="openCreate">新建合同</button></header><p v-if="error" class="form-tip">{{ error }}</p><FilterBar v-model:keyword="keyword" :busy="loading" placeholder="合同编号、合同名称或租户" @query="load" @reset="() => { keyword=''; status=''; load() }"><label class="field inline"><span>状态</span><select v-model="status"><option value="">全部</option><option>DRAFT</option><option>ACTIVE</option><option>TERMINATED</option></select></label></FilterBar><AppDataTable title="租户合同列表" :columns="columns" :rows="rows" :loading="loading" :error="error" @detail="openDetail" @refresh="load"><template #actions="{ row }"><button class="link-btn" @click="openDetail(row)">详情</button><button v-if="row.status==='DRAFT'" class="link-btn" @click="action(row,'activate')">生效</button><button v-if="row.status==='ACTIVE'" class="link-btn" @click="action(row,'terminate')">终止</button></template></AppDataTable><AppDialog v-model:open="dialog" :title="form.id ? '合同详情/编辑' : '新建合同'" description="草稿可编辑；生效时校验空间和结算表计冲突。" :saving="saving" @submit="save"><div class="dialog-fields contract-form"><div class="form-grid"><label class="dialog-field"><span>合同编号</span><input v-model="form.contractNo" :disabled="Boolean(form.id)"></label><label class="dialog-field"><span>合同名称</span><input v-model="form.contractName"></label><label class="dialog-field"><span>租户</span><select v-model="form.tenantId"><option value="">请选择</option><option v-for="x in tenants" :key="String(x.id)" :value="String(x.id)">{{ x.tenant_name }}</option></select></label><label class="dialog-field"><span>园区</span><select v-model="form.orgId"><option value="">请选择</option><option v-for="x in orgs" :key="String(x.id)" :value="String(x.id)">{{ x.org_name }}</option></select></label><label class="dialog-field"><span>开始日期</span><input v-model="form.startDate" type="date"></label><label class="dialog-field"><span>结束日期</span><input v-model="form.endDate" type="date"></label></div><h3>签约空间</h3><div class="checks"><label v-for="x in filteredSpaces" :key="String(x.id)"><input v-model="form.spaceIds" type="checkbox" :value="String(x.id)">{{ x.space_code }} · {{ x.space_name }}</label></div><h3>结算表计</h3><div class="checks meter-checks"><label v-for="x in meters" :key="String(x.id)"><input v-model="form.meterIds" type="checkbox" :value="String(x.id)" @change="ensureMeterFactor(String(x.id))"><span>{{ x.device_sn }} · {{ x.device_name }}</span><input v-if="form.meterIds.includes(String(x.id))" v-model.number="meterFactors[String(x.id)]" type="number" min="0.000001" step="0.000001" title="该合同结算倍率"></label></div></div></AppDialog></section></template>
<style scoped>.form-tip{color:#b54708}.contract-form{min-width:min(800px,78vw)}.checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:8px 0 18px}.checks label{padding:8px;border:1px solid var(--border);border-radius:6px}.meter-checks label{display:grid;grid-template-columns:auto 1fr 110px;align-items:center;gap:7px}.meter-checks input[type='number']{width:100%}</style>
