import type { RecordRow } from '@/types/domain'
import type { TableColumn } from '@/components/app/AppDataTable.vue'

export interface FormField { key: string; label: string; type?: 'text' | 'number' | 'textarea' | 'select' | 'date'; required?: boolean; options?: Array<{ label: string; value: string | number }> }
export interface ResourceSchema { title: string; description: string; area: 'archive' | 'billing'; resource: string; columns: TableColumn[]; fields: FormField[]; defaults: RecordRow }
const binary = [{ label: '启用', value: 1 }, { label: '停用', value: 0 }]
const tenantTypeOptions = [{ label: '企业', value: 'ENTERPRISE' }, { label: '个人', value: 'INDIVIDUAL' }]
const spaceTypeOptions = [
  { label: '楼宇', value: 'BUILDING' },
  { label: '楼层', value: 'FLOOR' },
  { label: '房间', value: 'ROOM' },
  { label: '商铺', value: 'SHOP' },
  { label: '停车位', value: 'PARKING' },
  { label: '其他', value: 'OTHER' },
]
const spaceStatusOptions = [
  { label: '空置', value: 'VACANT' },
  { label: '已占用', value: 'OCCUPIED' },
  { label: '停用', value: 'DISABLED' },
]

export const resourceSchemas: Record<string, ResourceSchema> = {
  orgs: { title: '组织管理', description: '组织层级维护。', area: 'archive', resource: 'orgs', columns: [{ key: 'org_name', label: '组织名称' }, { key: 'org_type', label: '组织类型' }, { key: 'leader', label: '负责人' }, { key: 'phone', label: '联系电话' }, { key: 'address', label: '地址' }], fields: [{ key: 'parent_id', label: '上级组织 ID', type: 'number' }, { key: 'org_name', label: '组织名称', required: true }, { key: 'org_type', label: '组织类型', type: 'number', required: true }, { key: 'leader', label: '负责人' }, { key: 'phone', label: '联系电话' }, { key: 'address', label: '地址', type: 'textarea' }], defaults: { parent_id: 0, org_name: '', org_type: 1, leader: '', phone: '', address: '' } },
  gateways: { title: '网关管理', description: '网关主数据管理。', area: 'archive', resource: 'gateways', columns: [{ key: 'gateway_sn', label: '网关编号' }, { key: 'gateway_name', label: '网关名称' }, { key: 'org_id', label: '所属组织' }, { key: 'online_status', label: '在线状态' }, { key: 'last_online_time', label: '最后在线时间' }], fields: [{ key: 'gateway_sn', label: '网关编号', required: true }, { key: 'gateway_name', label: '网关名称', required: true }, { key: 'mqtt_secret', label: 'MQTT 密钥', required: true }, { key: 'org_id', label: '组织 ID', type: 'number', required: true }, { key: 'install_location', label: '安装位置' }, { key: 'ip_address', label: 'IP 地址' }, { key: 'heartbeat_interval', label: '心跳间隔（秒）', type: 'number' }, { key: 'status', label: '启用状态', type: 'select', options: binary }], defaults: { gateway_sn: '', gateway_name: '', mqtt_secret: '', org_id: '', install_location: '', ip_address: '', heartbeat_interval: 60, status: 1 } },
  devices: { title: '设备管理', description: '设备主数据管理。采集周期和完整率阈值是结算数据质量的基准。', area: 'archive', resource: 'devices', columns: [{ key: 'device_sn', label: '设备编号' }, { key: 'device_name', label: '设备名称' }, { key: 'gateway_id', label: '网关 ID' }, { key: 'org_id', label: '组织 ID' }, { key: 'device_type_id', label: '设备类型' }, { key: 'collect_interval_seconds', label: '采集周期(秒)' }, { key: 'quality_threshold_pct', label: '完整率阈值(%)' }, { key: 'status', label: '状态' }], fields: [{ key: 'device_sn', label: '设备编号', required: true }, { key: 'device_name', label: '设备名称', required: true }, { key: 'gateway_id', label: '网关 ID', type: 'number', required: true }, { key: 'org_id', label: '组织 ID', type: 'number', required: true }, { key: 'device_type_id', label: '设备类型 ID', type: 'number', required: true }, { key: 'protocol_addr', label: '协议地址' }, { key: 'install_location', label: '安装位置' }, { key: 'device_model', label: '设备型号' }, { key: 'collect_interval_seconds', label: '采集周期（秒）', type: 'number', required: true }, { key: 'quality_threshold_pct', label: '日结算最低完整率（%）', type: 'number', required: true }, { key: 'status', label: '启用状态', type: 'select', options: binary }], defaults: { device_sn: '', device_name: '', gateway_id: '', org_id: '', device_type_id: '', protocol_addr: '', install_location: '', device_model: '', collect_interval_seconds: 300, quality_threshold_pct: 80, status: 1 } },
  spaces: { title: '空间台账', description: '园区空间台账。用于合同签约和空间归属管理。', area: 'archive', resource: 'spaces', columns: [{ key: 'space_code', label: '空间编码' }, { key: 'space_name', label: '空间名称' }, { key: 'space_type', label: '空间类型' }, { key: 'org_id', label: '所属组织' }, { key: 'active_contract_count', label: '生效合同' }, { key: 'device_count', label: '绑定设备' }, { key: 'status', label: '状态' }], fields: [{ key: 'org_id', label: '所属组织 ID', type: 'number', required: true }, { key: 'parent_id', label: '上级空间 ID', type: 'number' }, { key: 'space_code', label: '空间编码', required: true }, { key: 'space_name', label: '空间名称', required: true }, { key: 'space_type', label: '空间类型', type: 'select', required: true, options: spaceTypeOptions }, { key: 'building_no', label: '楼栋号' }, { key: 'floor_no', label: '楼层号' }, { key: 'area', label: '建筑面积', type: 'number' }, { key: 'rentable_area', label: '可租面积', type: 'number' }, { key: 'status', label: '状态', type: 'select', options: spaceStatusOptions }, { key: 'remark', label: '备注', type: 'textarea' }], defaults: { org_id: '', parent_id: 0, space_code: '', space_name: '', space_type: 'BUILDING', building_no: '', floor_no: '', area: '', rentable_area: '', status: 'VACANT', remark: '' } },
  'device-types': { title: '设备类型', description: '设备类型定义。', area: 'archive', resource: 'device-types', columns: [{ key: 'type_code', label: '类型编码' }, { key: 'type_name', label: '类型名称' }, { key: 'protocol_type', label: '协议类型' }, { key: 'enabled', label: '启用' }], fields: [{ key: 'type_code', label: '类型编码', required: true }, { key: 'type_name', label: '类型名称', required: true }, { key: 'protocol_type', label: '协议类型', type: 'select', options: [{ label: 'JSON', value: 'JSON' }, { label: 'MODBUS', value: 'MODBUS' }] }, { key: 'description', label: '说明', type: 'textarea' }, { key: 'enabled', label: '启用状态', type: 'select', options: binary }], defaults: { type_code: '', type_name: '', protocol_type: 'JSON', description: '', enabled: 1 } },
  'point-definitions': { title: '测点定义', description: '测点标准定义。', area: 'archive', resource: 'point-definitions', columns: [{ key: 'device_type_id', label: '设备类型' }, { key: 'point_code', label: '测点编码' }, { key: 'point_name', label: '测点名称' }, { key: 'data_type', label: '数据类型' }, { key: 'unit', label: '单位' }, { key: 'billable', label: '可计费' }], fields: [{ key: 'device_type_id', label: '设备类型 ID', type: 'number', required: true }, { key: 'point_code', label: '测点编码', required: true }, { key: 'point_name', label: '测点名称', required: true }, { key: 'data_type', label: '数据类型', type: 'select', options: [{ label: 'DOUBLE', value: 'DOUBLE' }, { label: 'INTEGER', value: 'INTEGER' }, { label: 'STRING', value: 'STRING' }] }, { key: 'unit', label: '单位' }, { key: 'business_role', label: '业务角色' }, { key: 'billable', label: '可计费', type: 'select', options: binary }, { key: 'stat_enabled', label: '纳入统计', type: 'select', options: binary }, { key: 'enabled', label: '启用状态', type: 'select', options: binary }], defaults: { device_type_id: '', point_code: '', point_name: '', data_type: 'DOUBLE', unit: '', business_role: '', billable: 0, stat_enabled: 1, enabled: 1 } },
  'point-mappings': { title: '协议映射', description: '测点协议映射。', area: 'archive', resource: 'point-mappings', columns: [{ key: 'device_type_id', label: '设备类型' }, { key: 'point_code', label: '测点编码' }, { key: 'protocol_type', label: '协议' }, { key: 'source_path', label: '来源路径' }, { key: 'required', label: '必填' }], fields: [{ key: 'device_type_id', label: '设备类型 ID', type: 'number', required: true }, { key: 'point_code', label: '测点编码', required: true }, { key: 'protocol_type', label: '协议类型', type: 'select', options: [{ label: 'JSON', value: 'JSON' }, { label: 'MODBUS', value: 'MODBUS' }] }, { key: 'source_path', label: 'JSONPath / 来源路径', required: true }, { key: 'scale_factor', label: '缩放系数', type: 'number' }, { key: 'offset_value', label: '偏移量', type: 'number' }, { key: 'required', label: '是否必填', type: 'select', options: binary }], defaults: { device_type_id: '', point_code: '', protocol_type: 'JSON', source_path: '$.', scale_factor: 1, offset_value: 0, required: 1 } },
  accounts: { title: '计费账户', description: '计费账户管理。', area: 'billing', resource: 'accounts', columns: [{ key: 'account_name', label: '账户名称' }, { key: 'org_id', label: '组织 ID' }, { key: 'contact_name', label: '联系人' }, { key: 'contact_phone', label: '联系电话' }, { key: 'status', label: '状态' }], fields: [{ key: 'account_name', label: '账户名称', required: true }, { key: 'org_id', label: '组织 ID', type: 'number', required: true }, { key: 'contact_name', label: '联系人' }, { key: 'contact_phone', label: '联系电话' }, { key: 'status', label: '启用状态', type: 'select', options: binary }], defaults: { account_name: '', org_id: '', contact_name: '', contact_phone: '', status: 1 } },
  tenants: { title: '租户档案', description: '租户主数据管理。用于合同、计费和结算归档。', area: 'billing', resource: 'tenants', columns: [{ key: 'tenant_code', label: '租户编码' }, { key: 'tenant_name', label: '租户名称' }, { key: 'tenant_type', label: '租户类型' }, { key: 'contact_name', label: '联系人' }, { key: 'contact_phone', label: '联系电话' }, { key: 'status', label: '状态' }], fields: [{ key: 'tenant_code', label: '租户编码', required: true }, { key: 'tenant_name', label: '租户名称', required: true }, { key: 'tenant_type', label: '租户类型', type: 'select', required: true, options: tenantTypeOptions }, { key: 'unified_social_credit_code', label: '统一社会信用代码' }, { key: 'contact_name', label: '联系人', required: true }, { key: 'contact_phone', label: '联系电话', required: true }, { key: 'contact_email', label: '联系邮箱' }, { key: 'billing_address', label: '开票地址', type: 'textarea' }, { key: 'status', label: '状态', type: 'select', options: [{ label: '启用', value: 'ACTIVE' }, { label: '停用', value: 'DISABLED' }] }, { key: 'remark', label: '备注', type: 'textarea' }], defaults: { tenant_code: '', tenant_name: '', tenant_type: 'ENTERPRISE', unified_social_credit_code: '', contact_name: '', contact_phone: '', contact_email: '', billing_address: '', status: 'ACTIVE', remark: '' } },
  rules: { title: '计费规则', description: '计费规则配置。', area: 'billing', resource: 'rules', columns: [{ key: 'rule_name', label: '规则名称' }, { key: 'account_id', label: '计费账户' }, { key: 'device_type_id', label: '设备类型' }, { key: 'metric_point_code', label: '计费测点' }, { key: 'price_mode', label: '计价方式' }, { key: 'enabled', label: '启用' }], fields: [{ key: 'account_id', label: '账户 ID', type: 'number', required: true }, { key: 'rule_name', label: '规则名称', required: true }, { key: 'device_type_id', label: '设备类型 ID', type: 'number', required: true }, { key: 'metric_point_code', label: '计费测点', required: true }, { key: 'billing_cycle', label: '计费周期', type: 'select', options: [{ label: 'MONTHLY', value: 'MONTHLY' }, { label: 'DAILY', value: 'DAILY' }] }, { key: 'price_mode', label: '计价方式', type: 'select', options: [{ label: '单价', value: 'UNIT_PRICE' }, { label: '固定', value: 'FIXED' }, { label: '阶梯', value: 'TIERED' }, { label: '分时', value: 'TIME_PERIOD' }] }, { key: 'enabled', label: '启用状态', type: 'select', options: binary }, { key: 'remark', label: '备注', type: 'textarea' }], defaults: { account_id: '', rule_name: '', device_type_id: '', metric_point_code: '', billing_cycle: 'MONTHLY', price_mode: 'UNIT_PRICE', enabled: 1, remark: '' } },
  'rule-scopes': { title: '规则适用范围', description: '规则范围管理。', area: 'billing', resource: 'rule-scopes', columns: [{ key: 'rule_id', label: '规则 ID' }, { key: 'scope_type', label: '范围类型' }, { key: 'scope_id', label: '范围对象 ID' }], fields: [{ key: 'rule_id', label: '规则 ID', type: 'number', required: true }, { key: 'scope_type', label: '范围类型', type: 'select', required: true, options: [{ label: '组织', value: 'ORG' }, { label: '设备', value: 'DEVICE' }] }, { key: 'scope_id', label: '组织 / 设备 ID', type: 'number', required: true }], defaults: { rule_id: '', scope_type: 'ORG', scope_id: '' } },
  'price-items': { title: '阶梯价格明细', description: '阶梯价格配置。', area: 'billing', resource: 'price-items', columns: [{ key: 'rule_id', label: '规则 ID' }, { key: 'price_label', label: '价格标签' }, { key: 'tier_min', label: '阶梯下限' }, { key: 'tier_max', label: '阶梯上限' }, { key: 'unit_price', label: '单价' }], fields: [{ key: 'rule_id', label: '规则 ID', type: 'number', required: true }, { key: 'price_label', label: '价格标签', required: true }, { key: 'tier_min', label: '阶梯下限', type: 'number' }, { key: 'tier_max', label: '阶梯上限', type: 'number' }, { key: 'unit_price', label: '单价', type: 'number', required: true }, { key: 'start_time', label: '分时开始（HH:mm）' }, { key: 'end_time', label: '分时结束（HH:mm）' }, { key: 'sort', label: '排序', type: 'number' }], defaults: { rule_id: '', price_label: '', tier_min: 0, tier_max: '', unit_price: 0, start_time: '', end_time: '', sort: 0 } },
}
