import { json, request, toQuery } from './http'
import type { PageResult } from '@/types/api'
import type { RecordRow } from '@/types/domain'

export const listResource = (area: 'archive' | 'billing', resource: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/${area}/${resource}${toQuery(params)}`)
export const getResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<RecordRow>(`/${area}/${resource}/${id}`)
export const createResource = (area: 'archive' | 'billing', resource: string, body: RecordRow) => request<RecordRow>(`/${area}/${resource}`, { method: 'POST', ...json(body) })
export const updateResource = (area: 'archive' | 'billing', resource: string, id: unknown, body: RecordRow) => request<RecordRow>(`/${area}/${resource}/${id}`, { method: 'PUT', ...json(body) })
export const removeResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<void>(`/${area}/${resource}/${id}`, { method: 'DELETE' })
export const archiveTree = () => request<RecordRow[]>('/archive/org-tree')
export const rootOrgs = () => request<RecordRow[]>('/archive/root-orgs')
export const deviceTree = (params: Record<string, unknown> = {}) => request<RecordRow[]>(`/archive/device-tree${toQuery(params)}`)
export const deviceProfile = (id: unknown) => request<RecordRow>(`/archive/devices/${id}/profile`)
export const deviceArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/devices/${id}/archive-profile`)
export const orgArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/orgs/${id}/archive-profile`)
export const gatewayArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/gateways/${id}/archive-profile`)
export const copyResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<RecordRow>(`/${area}/${resource}/${id}/copy`, { method: 'POST' })
export const deviceTypePoints = (id: unknown) => request<RecordRow>(`/archive/device-types/${id}/points`)
export const saveDeviceTypePoints = (id: unknown, body: RecordRow) => request<RecordRow>(`/archive/device-types/${id}/points/batch`, { method: 'POST', ...json(body) })
export const parsePoints = (body: RecordRow) => request<RecordRow>('/archive/point-mappings/parse-test', { method: 'POST', ...json(body) })
export const cockpit = () => request<RecordRow>('/workspace/cockpit')
export const dashboard = () => request<RecordRow>('/dashboard/summary')
export const monitor = (params: Record<string, unknown>) => request<RecordRow>(`/workspace/monitor${toQuery(params)}`)
export const energy = (path: string, params: Record<string, unknown> = {}) => request<RecordRow | RecordRow[]>(`/energy/${path}${toQuery(params)}`)
export const statistics = (path: string, params: Record<string, unknown> = {}) => request<RecordRow | RecordRow[]>(`/statistics/${path}${toQuery(params)}`)
export const alarmEvents = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/alarms/events${toQuery(params)}`)
export const alarmSummary = (params: Record<string, unknown> = {}) => request<RecordRow>(`/alarms/summary${toQuery(params)}`)
export const alarmRules = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/alarms/rules${toQuery(params)}`)
export const saveAlarmRule = (body: RecordRow, id?: unknown) => request<RecordRow>(id ? `/alarms/rules/${id}` : '/alarms/rules', { method: id ? 'PUT' : 'POST', ...json(body) })
export const dealAlarm = (id: unknown, body: RecordRow) => request<RecordRow>(`/alarms/events/${id}/deal`, { method: 'POST', ...json(body) })
export const batchDeal = (alarmIds: unknown[], body: RecordRow) => request<RecordRow[]>('/alarms/events/batch-deal', { method: 'POST', ...json({ alarmIds, ...body }) })
export const bills = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/bills${toQuery(params)}`)
export const bill = (id: unknown) => request<RecordRow>(`/billing/bills/${id}`)
export const billPreview = (body: RecordRow) => request<RecordRow>('/billing/bills/preview', { method: 'POST', ...json(body) })
export const generateBill = (body: RecordRow) => request<RecordRow>('/billing/bills/generate', { method: 'POST', ...json(body) })
export const payBill = (id: unknown, body: RecordRow) => request<RecordRow>(`/billing/bills/${id}/pay`, { method: 'POST', ...json(body) })
export const billAction = (id: unknown, action: 'recalculate' | 'void', body: RecordRow = {}) => request<RecordRow>(`/billing/bills/${id}/${action}`, { method: 'POST', ...json(body) })
export const access = (path: string, params: Record<string, unknown> = {}) => request<RecordRow>(`/access/${path}${toQuery(params)}`)
export const sendCommand = (body: RecordRow) => request<RecordRow>('/workspace/commands', { method: 'POST', ...json(body) })
export const rbac = (path: string, init: RequestInit = {}) => request<RecordRow | RecordRow[]>(`/rbac/${path}`, init)
export const rbacPage = (path: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/rbac/${path}${toQuery(params)}`)
export const rbacRelations = () => request<RecordRow>('/rbac/relations')
export const assignUserRoles = (id: unknown, ids: unknown[]) => request<void>(`/rbac/users/${id}/roles`, { method: 'POST', ...json({ ids }) })
export const assignRolePermissions = (id: unknown, ids: unknown[]) => request<void>(`/rbac/roles/${id}/permissions`, { method: 'POST', ...json({ ids }) })
export const rbacOrgTree = () => request<RecordRow[]>('/rbac/org-tree')
export const userOrgScopes = (id: unknown) => request<RecordRow[]>(`/rbac/users/${id}/org-scopes`)
export const assignUserOrgScopes = (id: unknown, scopes: RecordRow[]) => request<void>(`/rbac/users/${id}/org-scopes`, { method: 'PUT', ...json({ scopes }) })
export const audit = (path: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/audit/${path}${toQuery(params)}`)
