import { json, request, toQuery } from './http'
import type { PageResult } from '@/types/api'
import type { RecordRow } from '@/types/domain'

export const listResource = (area: 'archive' | 'billing', resource: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/${area}/${resource}${toQuery(params)}`)
export const getResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<RecordRow>(`/${area}/${resource}/${id}`)
export const createResource = (area: 'archive' | 'billing', resource: string, body: RecordRow) => request<RecordRow>(`/${area}/${resource}`, { method: 'POST', ...json(body) })
export const updateResource = (area: 'archive' | 'billing', resource: string, id: unknown, body: RecordRow) => request<RecordRow>(`/${area}/${resource}/${id}`, { method: 'PUT', ...json(body) })
export const removeResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<void>(`/${area}/${resource}/${id}`, { method: 'DELETE' })
export const archiveTree = () => request<RecordRow[]>('/archive/org-tree')
export const rootOrgs = () => request<RecordRow[]>('/archive/root-orgs')
export const deviceTree = (params: Record<string, unknown> = {}) => request<RecordRow[]>(`/archive/device-tree${toQuery(params)}`)
export const deviceProfile = (id: unknown) => request<RecordRow>(`/archive/devices/${id}/profile`)
export const deviceArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/devices/${id}/archive-profile`)
export const orgArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/orgs/${id}/archive-profile`)
export const gatewayArchiveProfile = (id: unknown) => request<RecordRow>(`/archive/gateways/${id}/archive-profile`)
export const copyResource = (area: 'archive' | 'billing', resource: string, id: unknown) => request<RecordRow>(`/${area}/${resource}/${id}/copy`, { method: 'POST' })
export const bindDevicesToGateway = (gatewayId: unknown, ids: unknown[]) => request<RecordRow[]>(`/archive/gateways/${gatewayId}/bind-devices`, { method: 'POST', ...json({ ids }) })
export const deviceTypePoints = (id: unknown) => request<RecordRow>(`/archive/device-types/${id}/points`)
export const saveDeviceTypePoints = (id: unknown, body: RecordRow) => request<RecordRow>(`/archive/device-types/${id}/points/batch`, { method: 'POST', ...json(body) })
export const parsePoints = (body: RecordRow) => request<RecordRow>('/archive/point-mappings/parse-test', { method: 'POST', ...json(body) })
export const cockpit = (params: Record<string, unknown> = {}) => request<RecordRow>(`/workspace/cockpit${toQuery(params)}`)
export const businessWorkspace = (key: 'archive' | 'alarms' | 'billing') => request<RecordRow>(`/workspace/${key}`)
export const dashboard = (params: Record<string, unknown> = {}) => request<RecordRow>(`/dashboard/summary${toQuery(params)}`)
export const experienceAssets = (params: Record<string, unknown> = {}) => request<RecordRow>(`/experience/assets${toQuery(params)}`)
export const experienceOperations = (params: Record<string, unknown> = {}) => request<RecordRow>(`/experience/operations${toQuery(params)}`)
export const experienceRevenue = (params: Record<string, unknown> = {}) => request<RecordRow>(`/experience/revenue${toQuery(params)}`)
export const experienceRevenuePrecheck = (params: Record<string, unknown>) => request<RecordRow>(`/experience/revenue/precheck${toQuery(params)}`)
export const monitor = (params: Record<string, unknown>) => request<RecordRow>(`/workspace/monitor${toQuery(params)}`)
export const energy = (path: string, params: Record<string, unknown> = {}) => request<RecordRow | RecordRow[]>(`/energy/${path}${toQuery(params)}`)
export const statistics = (path: string, params: Record<string, unknown> = {}) => request<RecordRow | RecordRow[]>(`/statistics/${path}${toQuery(params)}`)
export const dataQualitySummary = () => request<RecordRow>('/data-quality/summary')
export const dataQualityEvents = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/data-quality/events${toQuery(params)}`)
export const dataQualityEvent = (id: unknown) => request<RecordRow>(`/data-quality/events/${id}`)
export const replayDataQualityEvent = (id: unknown) => request<RecordRow>(`/data-quality/events/${id}/replay`, { method: 'POST' })
export const collectionQualityDaily = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/data-quality/collection-daily${toQuery(params)}`)
export const workOrders = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/operations/work-orders${toQuery(params)}`)
export const workOrder = (id: unknown) => request<RecordRow>(`/operations/work-orders/${id}`)
export const createWorkOrder = (body: RecordRow) => request<RecordRow>('/operations/work-orders', { method: 'POST', ...json(body) })
export const workOrderAction = (id: unknown, action: string, body: RecordRow = {}) => request<RecordRow>(`/operations/work-orders/${id}/${action}`, { method: 'POST', ...json(body) })
export const operationAssignees = (params: Record<string, unknown>) => request<RecordRow[]>(`/operations/assignees${toQuery(params)}`)
export const createAlarmWorkOrder = (alarmId: unknown) => request<RecordRow>(`/alarms/events/${alarmId}/work-order`, { method: 'POST' })
export const inspectionPlans = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/operations/inspection-plans${toQuery(params)}`)
export const saveInspectionPlan = (body: RecordRow, id?: unknown) => request<RecordRow>(id ? `/operations/inspection-plans/${id}` : '/operations/inspection-plans', { method: id ? 'PUT' : 'POST', ...json(body) })
export const inspectionTasks = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/operations/inspection-tasks${toQuery(params)}`)
export const generateInspectionTasks = (taskDate?: string) => request<RecordRow>(`/operations/inspection-tasks/generate${toQuery({ taskDate })}`, { method: 'POST' })
export const executeInspection = (id: unknown, body: RecordRow) => request<RecordRow>(`/operations/inspection-tasks/${id}/execute`, { method: 'POST', ...json(body) })
export const alarmEvents = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/alarms/events${toQuery(params)}`)
export const alarmSummary = (params: Record<string, unknown> = {}) => request<RecordRow>(`/alarms/summary${toQuery(params)}`)
export const alarmRules = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/alarms/rules${toQuery(params)}`)
export const saveAlarmRule = (body: RecordRow, id?: unknown) => request<RecordRow>(id ? `/alarms/rules/${id}` : '/alarms/rules', { method: id ? 'PUT' : 'POST', ...json(body) })
export const dealAlarm = (id: unknown, body: RecordRow) => request<RecordRow>(`/alarms/events/${id}/deal`, { method: 'POST', ...json(body) })
export const batchDeal = (alarmIds: unknown[], body: RecordRow) => request<RecordRow[]>('/alarms/events/batch-deal', { method: 'POST', ...json({ alarmIds, ...body }) })
export const bills = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/bills${toQuery(params)}`)
export const bill = (id: unknown) => request<RecordRow>(`/billing/bills/${id}`)
export const billPreview = (body: RecordRow) => request<RecordRow>('/billing/bills/preview', { method: 'POST', ...json(body) })
export const generateBill = (body: RecordRow) => request<RecordRow>('/billing/bills/generate', { method: 'POST', ...json(body) })
export const payBill = (id: unknown, body: RecordRow) => request<RecordRow>(`/billing/bills/${id}/pay`, { method: 'POST', ...json(body) })
export const billAction = (id: unknown, action: 'recalculate' | 'void', body: RecordRow = {}) => request<RecordRow>(`/billing/bills/${id}/${action}`, { method: 'POST', ...json(body) })
export const reversePayment = (id: unknown, body: RecordRow) => request<RecordRow>(`/billing/payments/${id}/reverse`, { method: 'POST', ...json(body) })
export const billingAdjustments = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/adjustments${toQuery(params)}`)
export const createBillingAdjustment = (body: RecordRow) => request<RecordRow>('/billing/adjustments', { method: 'POST', ...json(body) })
export const billingAdjustmentAction = (id: unknown, action: 'approve' | 'cancel', body: RecordRow = {}) => request<RecordRow>(`/billing/adjustments/${id}/${action}`, { method: 'POST', ...json(body) })
export const meterChangeOrders = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/metering/orders${toQuery(params)}`)
export const meterChangeOrder = (id: unknown) => request<RecordRow>(`/billing/metering/orders/${id}`)
export const createMeterChangeOrder = (body: RecordRow) => request<RecordRow>('/billing/metering/orders', { method: 'POST', ...json(body) })
export const meterChangeAction = (id: unknown, action: 'approve' | 'reject' | 'cancel' | 'execute', body: RecordRow = {}) => request<RecordRow>(`/billing/metering/orders/${id}/${action}`, { method: 'POST', ...json(body) })
export const overdueBills = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/collections/overdue${toQuery(params)}`)
export const billCollections = (id: unknown) => request<RecordRow[]>(`/billing/bills/${id}/collections`)
export const createBillCollection = (id: unknown, body: RecordRow) => request<RecordRow>(`/billing/bills/${id}/collections`, { method: 'POST', ...json(body) })
export const tariffPlans = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/tariff-plans${toQuery(params)}`)
export const tariffPlan = (id: unknown) => request<RecordRow>(`/billing/tariff-plans/${id}`)
export const saveTariffPlan = (body: RecordRow, id?: unknown) => request<RecordRow>(id ? `/billing/tariff-plans/${id}` : '/billing/tariff-plans', { method: id ? 'PUT' : 'POST', ...json(body) })
export const validateTariffPlan = (body: RecordRow) => request<RecordRow>('/billing/tariff-plans/validate', { method: 'POST', ...json(body) })
export const tariffPlanAction = (id: unknown, action: 'enable' | 'disable' | 'copy-version', body: RecordRow = {}) => request<RecordRow>(`/billing/tariff-plans/${id}/${action}`, { method: 'POST', ...json(body) })
export const rebuildTouStatistics = (params: Record<string, unknown>) => request<RecordRow>(`/statistics/tou/rebuild${toQuery(params)}`, { method: 'POST' })
export const contracts = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/contracts${toQuery(params)}`)
export const contract = (id: unknown) => request<RecordRow>(`/billing/contracts/${id}`)
export const saveContract = (body: RecordRow, id?: unknown) => request<RecordRow>(id ? `/billing/contracts/${id}` : '/billing/contracts', { method: id ? 'PUT' : 'POST', ...json(body) })
export const contractAction = (id: unknown, action: 'activate' | 'terminate', body: RecordRow = {}) => request<RecordRow>(`/billing/contracts/${id}/${action}`, { method: 'POST', ...json(body) })
export const billingBatches = (params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/billing/batches${toQuery(params)}`)
export const saveBillingBatch = (body: RecordRow) => request<RecordRow>('/billing/batches', { method: 'POST', ...json(body) })
export const billingBatchAction = (id: unknown, action: 'generate' | 'review' | 'issue') => request<RecordRow>(`/billing/batches/${id}/${action}`, { method: 'POST' })
export const access = (path: string, params: Record<string, unknown> = {}) => request<RecordRow>(`/access/${path}${toQuery(params)}`)
export const sendCommand = (body: RecordRow) => request<RecordRow>('/workspace/commands', { method: 'POST', ...json(body) })
export const rbac = (path: string, init: RequestInit = {}) => request<RecordRow | RecordRow[]>(`/rbac/${path}`, init)
export const rbacPage = (path: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/rbac/${path}${toQuery(params)}`)
export const rbacRelations = () => request<RecordRow>('/rbac/relations')
export const assignUserRoles = (id: unknown, ids: unknown[]) => request<void>(`/rbac/users/${id}/roles`, { method: 'POST', ...json({ ids }) })
export const assignRolePermissions = (id: unknown, ids: unknown[]) => request<void>(`/rbac/roles/${id}/permissions`, { method: 'POST', ...json({ ids }) })
export const rbacOrgTree = () => request<RecordRow[]>('/rbac/org-tree')
export const userOrgScopes = (id: unknown) => request<RecordRow[]>(`/rbac/users/${id}/org-scopes`)
export const assignUserOrgScopes = (id: unknown, scopes: RecordRow[]) => request<void>(`/rbac/users/${id}/org-scopes`, { method: 'PUT', ...json({ scopes }) })
export const audit = (path: string, params: Record<string, unknown> = {}) => request<PageResult<RecordRow>>(`/audit/${path}${toQuery(params)}`)
export const catalogTree = (keyword = '') => request<RecordRow[]>(`/catalog/tree${toQuery({ keyword })}`)
export const catalogAttributeTree = () => request<RecordRow[]>('/catalog/attribute-tree')
export const catalogPointTree = () => request<RecordRow[]>('/catalog/point-tree')
export const catalogPointGroupCreate = (body: RecordRow) => request<RecordRow>('/catalog/point-groups', { method: 'POST', ...json(body) })
export const catalogLookups = () => request<RecordRow>('/catalog/lookups')
export const catalogModel = (id: unknown, versionId?: unknown) => request<RecordRow>(`/catalog/models/${id}${toQuery({ versionId })}`)
export const catalogCreate = (resource: 'categories' | 'brands' | 'series' | 'models' | 'attribute-groups' | 'attributes' | 'attribute-values' | 'standard-points' | 'point-groups', body: RecordRow) => request<RecordRow>(`/catalog/${resource}`, { method: 'POST', ...json(body) })
export const catalogUpdateNode = (nodeType: string, id: unknown, body: RecordRow) => request<RecordRow>(`/catalog/nodes/${nodeType}/${id}`, { method: 'PUT', ...json(body) })
export const catalogDeleteNode = (nodeType: string, id: unknown) => request<RecordRow>(`/catalog/nodes/${nodeType}/${id}`, { method: 'DELETE' })
export const catalogCreateVersion = (modelId: unknown, sourceVersionId?: unknown) => request<RecordRow>(`/catalog/models/${modelId}/versions${toQuery({ sourceVersionId })}`, { method: 'POST' })
export const catalogUpdateVersion = (versionId: unknown, body: RecordRow) => request<RecordRow>(`/catalog/versions/${versionId}`, { method: 'PUT', ...json(body) })
export const catalogSaveAttributes = (versionId: unknown, body: RecordRow[]) => request<RecordRow>(`/catalog/versions/${versionId}/attributes`, { method: 'PUT', ...json(body) })
export const catalogSavePoints = (versionId: unknown, body: RecordRow[]) => request<RecordRow>(`/catalog/versions/${versionId}/points`, { method: 'PUT', ...json(body) })
export const catalogVersionAction = (versionId: unknown, action: 'validate' | 'publish' | 'disable') => request<RecordRow>(`/catalog/versions/${versionId}/${action}`, { method: 'POST' })
export const catalogDeleteVersion = (versionId: unknown) => request<RecordRow>(`/catalog/versions/${versionId}`, { method: 'DELETE' })
export const publishedModelOptions = () => request<RecordRow[]>('/catalog/published-options')
export const provisionDevice = (body: RecordRow) => request<RecordRow>('/devices/provision', { method: 'POST', ...json(body) })
export const updateDeviceContext = (id: unknown, body: RecordRow) => request<RecordRow>(`/devices/${id}/context`, { method: 'PUT', ...json(body) })
export const saveDeviceAttributeOverrides = (id: unknown, values: RecordRow[]) => request<RecordRow[]>(`/devices/${id}/attributes`, { method: 'PUT', ...json({ values }) })
export const deployDevice = (id: unknown, body: RecordRow) => request<RecordRow>(`/devices/${id}/deployment`, { method: 'PUT', ...json(body) })
export const unbindDevice = (id: unknown, body: RecordRow = {}) => request<RecordRow>(`/devices/${id}/unbind`, { method: 'POST', ...json(body) })
